### ISSUE TITLE
I am not getting audio input in video call sometime

### ISSUE THREAD

**Issue by devgeektech** [QuickBlox/quickblox-ios-sdk#1196] opened 2020-03-31 13:22 UTC
Hello Guys

I am able to make video call, everything is working fine in first call but in second or third time, audio is not coming from second device. Please help me out for this issue, you can check my code below:-

```

import UIKit
import Quickblox
import QuickbloxWebRTC
import CallKit
import PushKit
import AVFoundation
protocol QuickBloxManagerDelegate:class {
    func steamVideoTrack(_ track: QBRTCVideoTrack)
    func callingState(_ state:QBRTCSessionState)
    func userConnected()
}
typealias CallBackAction = () -> ()

class QuickBloxManager:NSObject{
    var users = [QBUUser]()
    var videoCapture: QBRTCCameraCapture?
    var session: QBRTCSession?
    var uuid: UUID?
    
    lazy private var voipRegistry: PKPushRegistry = {
        let voipRegistry = PKPushRegistry(queue: DispatchQueue.main)
        return voipRegistry
    }()
    lazy private var backgroundTask: UIBackgroundTaskIdentifier = {
        let backgroundTask = UIBackgroundTaskIdentifier.invalid
        return backgroundTask
    }()
    weak var delegate:QuickBloxManagerDelegate?
    init(_ delegate:QuickBloxManagerDelegate?) {
        self.delegate = delegate
        super.init()
       setupInit()
    }
    
    private func setupInit(){
        QBRTCClient.instance().add(self)
        
        voipRegistry.delegate = self
        voipRegistry.desiredPushTypes = Set<PKPushType>([.voIP])
        if let uu = UserDefaults.standard.value(forKey: "deviceToken") as? String{
            uuid = UUID(uuidString: uu)
        }
        setBasicRTCConfiguration()
//        QBRTCAudioSession.instance().initialize()
//        QBRTCAudioSession.instance().useManualAudio = true
//        QBRTCAudioSession.instance().currentAudioDevice = .speaker
//         QBRTCConfig.setMediaStreamConfiguration(mediaConfiguration)
    }
    func setBasicRTCConfiguration() {
           let conf = QBRTCMediaStreamConfiguration.default()
           conf.audioCodec = QBRTCAudioCodec.codeciLBC
           QBRTCConfig.setMediaStreamConfiguration(conf)
           
       }
    
    func signIn(fullName: String, login: String, password: String,completion: @escaping (Bool)->Void){
        QBRequest.logIn(withUserLogin: login,
                        password: password,
                        successBlock: { [weak self] response, user in
                            
                            user.password = password
                            user.updatedAt = Date()
                            self?.connectToChat(user: user, completion: {success in
                                if success{
                                    completion(true)
                                }else{
                                    completion(false)
                                }
                            })
                            
                            
            }, errorBlock: {response in
                
                if response.status == QBResponseStatusCode.unAuthorized {
                    // Clean profile
                    
                }
        })
    }
    
    func toggleSpeaker(){
        if  !QBRTCAudioSession.instance().isInitialized{
            QBRTCAudioSession.instance().initialize()
        }
        if QBRTCAudioSession.instance().currentAudioDevice == .speaker{
            QBRTCAudioSession.instance().currentAudioDevice = .receiver
        }else{
            QBRTCAudioSession.instance().currentAudioDevice = .speaker
        }
    }
    
    private func connectToChat(user: QBUUser, completion: @escaping (Bool)->Void) {
        
        QBChat.instance.connect(withUserID: user.id,
                                password: user.password!,
                                completion: {  error in
                                    if let error = error {
                                        if error._code == QBResponseStatusCode.unAuthorized.rawValue {
                                            // Clean profile
                                            completion(false)
                                        } else {
                                            completion(false)
                                            
                                        }
                                    } else {
                                        completion(true)
                                    }
        })
    }
    
    func startCall(opponets:[Int], completion: @escaping CallBackAction){
        
            // userInfo - the custom user information dictionary for the call. May be nil.
       
            CallKitManager.instance.startCall(withUserIDs: opponets as [NSNumber], session: self.session, uuid: self.uuid)
        
            completion()

    }
    func createSession(opponets:[Int]){
         self.session = QBRTCClient.instance().createNewSession(withOpponents: opponets as [NSNumber], with: .video)
    }
    
    func startCall() {
        //Begin play calling sound
       
        //Start call
        let userInfo = ["name": DataManager.fullName, "url": "http.quickblox.com"]
        
        session?.startCall(nil)
    }
    func acceptCall() {
          
           //Accept call
           let userInfo = ["acceptCall": "userInfo"]
           session?.acceptCall(nil)
       }
    func endCall(){
        let userInfo = ["name": DataManager.fullName, "url": "http.quickblox.com"]
        self.session?.hangUp(nil)
//        let uuid = UUID()
      
        QBRTCAudioSession.instance().deinitialize()
        QBRTCClient.instance().remove(self)
        CallKitManager.instance.endCall(with: uuid) {
            let window = UIApplication.shared.windows.first
            window?.rootViewController?.dismiss(animated: true, completion: nil)

        }
       self.session = nil
       
       
    }
    
    func steamLocalVideo(localView:UIView){
        let videoFormat = QBRTCVideoFormat.init()
        videoFormat.frameRate = 30
        videoFormat.pixelFormat = QBRTCPixelFormat.format420f
        videoFormat.width = UInt(localView.bounds.width)
        videoFormat.height = UInt(localView.bounds.height)
        
        // QBRTCCameraCapture class used to capture frames using AVFoundation APIs
        self.videoCapture = QBRTCCameraCapture.init(videoFormat: videoFormat, position: AVCaptureDevice.Position.front)
        
        // add video capture to session's local media stream
        // from version 2.3 you no longer need to wait for 'initializedLocalMediaStream:' delegate to do it
        if self.session != nil {
            
            self.session!.localMediaStream.videoTrack.videoCapture = self.videoCapture
            self.session?.localMediaStream.audioTrack.isEnabled = true
            self.videoCapture!.previewLayer.frame = localView.bounds
            self.videoCapture!.startSession()
            
            localView.layer.insertSublayer(self.videoCapture!.previewLayer, at: 0)
        }
        
    }
    
    func setupAudio() {
        
            QBRTCAudioSession.instance().initialize { (configuration) in
                
                if (self.session?.conferenceType == QBRTCConferenceType.video) {
                    configuration.mode = AVAudioSession.Mode.videoChat.rawValue
                }
            }
            QBRTCAudioSession.instance().currentAudioDevice = QBRTCAudioDevice.speaker
        
        
    }
    
    func loadUsers(_ completion: @escaping ([QBUUser]?, Bool)->Void) {
        let firstPage = QBGeneralResponsePage(currentPage: 1, perPage: 100)
        QBRequest.users(withExtendedRequest: ["order": "desc date updated_at"],
                        page: firstPage,
                        successBlock: { (response, page, users) in
                            completion(users, true)
                            
        }, errorBlock: { response in
            completion(nil, false)
            
            debugPrint("[UsersViewController] loadUsers error:")
        })
    }
    
    func outputStream(_ completion: @escaping (QBRTCVideoTrack)->Void) {
        
    }
    
    
}
extension QuickBloxManager:QBRTCClientDelegate{
    
   
    
    func didReceiveNewSession(_ session: QBRTCSession, userInfo: [String : String]? = nil) {
        print("QBRTCAudioSession.instance().currentAudioDevice--\(UIDevice().name)",QBRTCAudioSession.instance().currentAudioDevice)
      if self.session != nil {
            // we already have a video/audio call session, so we reject another one
            // userInfo - the custom user information dictionary for the call from caller. May be nil.
            let userInfo = ["key":"value"] // optional
             self.session?.rejectCall(nil)
            return
        }
         CallPermissions.check(with: .video) { [weak self](granted) in
            let remoteAudioTrack = self?.session?.remoteAudioTrack(withUserID: NSNumber(value: DataManager.opponentId))
            remoteAudioTrack?.isEnabled = true
            CallKitManager.instance.reportIncomingCall(withUserIDs: [NSNumber(value: DataManager.opponentId)], outCallerName: DataManager.fullName, session: session, uuid: self?.uuid, onAcceptAction: {
                
                   let window = UIApplication.shared.windows.first
                  let storyBoard : UIStoryboard = UIStoryboard(name:"Main", bundle: nil)
                   let conVC = storyBoard.instantiateViewController(withIdentifier: "VideoCallViewController") as? VideoCallViewController
                   conVC?.modalPresentationStyle = .overFullScreen
                   conVC?.modalTransitionStyle = .crossDissolve
                   conVC!.session = session
                   window?.rootViewController?.present(conVC!, animated: true, completion: nil)
                }, completion: { (end) in
                    debugPrint("[UsersViewController] endCall")
                })
        }
      

            
        
    }
    
    func session(_ session: QBRTCSession, acceptedByUser userID: NSNumber, userInfo: [String : String]? = nil) {
//        if  !QBRTCAudioSession.instance().isInitialized{
//            QBRTCAudioSession.instance().initialize()
//        }
//        if  QBRTCAudioSession.instance().currentAudioDevice == .receiver{
//            QBRTCAudioSession.instance().currentAudioDevice = .speaker
//        }
    }
    func session(_ session: QBRTCSession, hungUpByUser userID: NSNumber, userInfo: [String : String]? = nil) {
         self.session = nil
        CallKitManager.instance.endCall(with: uuid) {
//            let window = UIApplication.shared.windows.first
//            window?.rootViewController?.dismiss(animated: true, completion: nil)
//            let navController = UIApplication.shared.windows[0].rootViewController as? UINavigationController
//            navController?.popViewController(animated: true)
        }
        let window = UIApplication.shared.windows.first
                   window?.rootViewController?.dismiss(animated: true, completion: nil)
        
    }
    
    func session(_ session: QBRTCBaseSession, connectedToUser userID: NSNumber) {
        delegate?.userConnected()
        
        CallKitManager.instance.updateCall(with: self.uuid, connectedAt: Date())
    }
    
    func sessionDidClose(_ session: QBRTCSession) {
        self.session = nil
    }
    func session(_ session: QBRTCBaseSession, didChange state: QBRTCSessionState) {
      
        delegate?.callingState(state)
        switch state{
        case .new, .connecting:
            print("connecting")
        case .connected:
           
            let opponetid = NSNumber(value: DataManager.opponentId)
           
            if let remoteVideoTraсk = self.session?.remoteVideoTrack(withUserID: opponetid){
                
                delegate?.steamVideoTrack(remoteVideoTraсk)
            }
            
        
        default:
            let window = UIApplication.shared.windows.first
            window?.rootViewController?.dismiss(animated: true, completion: nil)
        }
        
    }
    
   
}
extension QuickBloxManager: PKPushRegistryDelegate {
    // MARK: - PKPushRegistryDelegate
    func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
        guard let deviceIdentifier = UIDevice.current.identifierForVendor?.uuidString else {
            return
        }
        let subscription = QBMSubscription()
        subscription.notificationChannel = .APNSVOIP
        subscription.deviceUDID = deviceIdentifier
        subscription.deviceToken = pushCredentials.token
        
        QBRequest.createSubscription(subscription, successBlock: { response, objects in
            debugPrint("[UsersViewController] Create Subscription request - Success")
        }, errorBlock: { response in
            debugPrint("[UsersViewController] Create Subscription request - Error")
        })
    }
    
    func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
        guard let deviceIdentifier = UIDevice.current.identifierForVendor?.uuidString else {
            return
        }
        QBRequest.unregisterSubscription(forUniqueDeviceIdentifier: deviceIdentifier, successBlock: { response in
            debugPrint("[UsersViewController] Unregister Subscription request - Success")
        }, errorBlock: { error in
            debugPrint("[UsersViewController] Unregister Subscription request - Error")
        })
    }
    
    func pushRegistry(_ registry: PKPushRegistry,
                      didReceiveIncomingPushWith payload: PKPushPayload,
                      for type: PKPushType) {
        if payload.dictionaryPayload["VOIPCall"] != nil {
            let application = UIApplication.shared
            if application.applicationState == .background && backgroundTask == .invalid {
                backgroundTask = application.beginBackgroundTask(expirationHandler: {
                    application.endBackgroundTask(self.backgroundTask)
                    self.backgroundTask = UIBackgroundTaskIdentifier.invalid
                })
            }
            if QBChat.instance.isConnected == false {
               
            }
        }
    }
}
```

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:42
@devgeektech The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:42 UTC
