### ISSUE TITLE
Inbox unread conversation counter in Swift

### ISSUE THREAD

**Issue by Awais987** [QuickBlox/quickblox-ios-sdk#1214] opened 2020-05-18 06:45 UTC
**New Issue Checklist**

 - [ yes ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ yes ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 13.4.1                                    |                                          
Quickblox iOS SDK version      | 2.17.4                                  |
QuickbloxWebRTC SDK version    | 2.7.4                                  |                               
Xcode Version                  | Xcode 11.4.1                              |
Repro with our demo sample     | I did't see anything related to this in your sample app other then single conversation counter.  |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:51
@Awais987 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:51 UTC
