### ISSUE TITLE
video call get disconnected automatically and gets crashed when video call is recieved from another user.

### ISSUE THREAD

**Issue by indraja-paramount** [QuickBlox/quickblox-ios-sdk#1245] opened 2020-10-17 08:47 UTC
This is my log

2020-10-16 18:19:25.289484+0530 sample-videochat-webrtc-swift[23410:1129005] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x60000145d860> to GL_RENDERBUFFER 1
2020-10-16 18:19:25.290350+0530 sample-videochat-webrtc-swift[23410:1129005] Failed to make complete framebuffer object 8cd6
2020-10-16 18:19:25.292 rtc::[Signaling Processor] - Did receive signal: iceCandidates from: 123313882
2020-10-16 18:19:25.292 rtc::[Signaling Processor] - Did receive signal: iceCandidates from: 123313882
2020-10-16 18:19:25.292 rtc::[Signaling Processor] - Did receive signal: hangUp from: 123313882
2020-10-16 18:19:25.292 rtc::[PCON]<123313882, R:Offer> Set remote ICE candidates, count: 1
2020-10-16 18:19:25.293 rtc::[PCON]<123313882, R:Offer> Did change ice connection state to COMPLETED
2020-10-16 18:19:25.303 rtc::[PCON]<123313882, R:Offer> Did change ice connection state to DISCONNECTED
2020-10-16 18:19:25.303 rtc::[PCON]<123313882, R:Offer> Did change ice connection state to FAILED
2020-10-16 18:19:25.310 rtc::[PCON]<123313882, R:Offer> Set remote ICE candidates, count: 1
2020-10-16 18:19:25.379 rtc::[PCON]<123313882, R:Offer> Closing
2020-10-16 18:19:25.397 rtc::[PCON]<123313882, R:Offer> Did change ice connection state to CLOSED
2020-10-16 18:19:25.397 rtc::[PCON]<123313882, R:Offer> Signaling state CLOSED

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:49
@indraja-paramount The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:49 UTC
