### ISSUE TITLE
iOS Build Error Using Quickblox Pod file in AWS Mobile SDK 

### ISSUE THREAD

**Issue by aanchalkalani** [QuickBlox/quickblox-ios-sdk#565] opened 2016-08-04 06:07 UTC
We have an iOS application that is referencing the AWS Mobile frameworks directly and several other libraries using CocoaPods. The project builds fine

But, when we add the 'Quickblox-SDK dynamic' as an additional library to reference in the PodFile and run pod install I get several build/linker errors:

`Undefined symbols for architecture x86_64:
  "_AWSSNSErrorDomain", referenced from:
      ___88-[AWSPushManager interceptApplication:didRegisterForRemoteNotificationsWithDeviceToken:]_block_invoke.239 in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNS", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSCreatePlatformEndpointInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSGetEndpointAttributesInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSSetEndpointAttributesInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSSubscribeInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_AWSSNSUnsubscribeInput", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSPushManager.o)
  "_OBJC_CLASS_$_FBSDKAccessToken", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_FBSDKApplicationDelegate", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_FBSDKGraphRequest", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_FBSDKLoginManager", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSFacebookSignInProvider.o)
  "_OBJC_CLASS_$_GIDSignIn", referenced from:
      objc-class-ref in AWSMobileHubHelper(AWSGoogleSignInProvider.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

If we remove the $(inherited) flag from the Other Linker Flags build setting, getting below errors:-

`bash: /User/..../AWSCore.framework/strip-frameworks.sh: No such file or directory uploadDSYM[13005:219405] Fabric.framework/run 1.4.1 (160) uploadDSYM[13005:219405] Launched uploader in validation mode bash: /Users/..../Frameworks/Quickblox.framework/strip-framework.sh: No such file or directory`

Any Help will be appreciated..

Thanks,

**Comment by Pro100Andrey** [comment] 2016-08-04 08:58
Hi @aanchalkalani, please provide pod file from your project

**Comment by Raikerian** [comment] 2016-08-04 09:15
Hi @aanchalkalani 

Have you added custom amazon script to Run Script Phase?
Script is here: AWSCore.framework/strip-frameworks.sh

It is stripping simulator symbols after every build for **all dynamic frameworks in project**. You should only use it when you are archiving your build for submitting into App Store (because app store will not allow you to upload binary with simulator symbols. Remove it in order to build and install your app on simulator.

**Comment by aanchalkalani** [comment] 2016-08-04 09:33
@Pro100Andrey  
 Pod file :-
 # Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
target 'MyApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for MyApp
	pod 'QuickBlox'
end

---------------------------------------------
@Raikerian My Script :- bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/AWSCore.framework/strip-frameworks.sh"

**Comment by Raikerian** [comment] 2016-08-04 09:34
@aanchalkalani Remove that script, the issue is there. Add it only when you will archive your app for appstore submission. I've explained you what it is doing in the post before your answer.

**Comment by Pro100Andrey** [comment] 2016-08-04 09:38
@aanchalkalani have we resolved your issue? if yes, please, close it

**Comment by aanchalkalani** [comment] 2016-08-04 14:09
:( 

1. After removing the Run Script Phase, and 
2. QuickBlox For dynamic framework add Quickblox as Embedded binary., 
3. I also remove $(inherited) from the Other Linker Flags

Getting Below errors 

```
ld: warning: Auto-Linking supplied '/Users/...../MyApp/Pods/QuickBlox/Quickblox.framework/Quickblox is not a dylib
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_QBChat", referenced from:
      type metadata accessor for __ObjC.QBChat in SignInViewController.o
  "_OBJC_CLASS_$_QBRequest", referenced from:
      type metadata accessor for __ObjC.QBRequest in SignInViewController.o
  "_OBJC_CLASS_$_QBSettings", referenced from:
      type metadata accessor for __ObjC.QBSettings in AppDelegate.o
  "_OBJC_CLASS_$_QBUUser", referenced from:
      type metadata accessor for __ObjC.QBUUser in SignInViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Raikerian** [comment] 2016-08-04 14:13
> I also remove $(inherited) from the Other Linker Flags

Why have you done that?
Remove all unnecessary scripts for stripping.

**Comment by aanchalkalani** [comment] 2016-08-05 04:45
I removed  all the scripts for stripping, still i am getting the errors. 

I removed :-
```
1.  bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Quickblox.framework/strip-framework.sh" 
2. bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/AWSCore.framework/strip-frameworks.sh"
3. FILE=${SRCROOT}/MyApp/Sdk/CheckXcodeVersion.sh
if [ -e $FILE ]; then
$FILE
fi
```

**Comment by Raikerian** [comment] 2016-08-05 08:11
@aanchalkalani I have just created a test project using Pod QuickBlox. Everything is working fine there. Try to recreate a project, or send us your test project to us so we can try to find the issue. But i'm definitely suggesting you to try first step.

**Comment by Raikerian** [comment] 2016-08-08 11:57
@aanchalkalani have you fixed this?

**Comment by aanchalkalani** [comment] 2016-08-11 08:24
No, i tried first step 2 or 3 times but  its given me same error. :(

**Comment by Raikerian** [comment] 2016-08-11 13:27
Can you try to reproduce it on test project and send it in this thread?

**Comment by VitaliyGuru** [comment] 2016-08-16 11:02
@aanchalkalani , any updates?

**Closed** 2016-10-06 17:04 UTC
Labels: question
