### ISSUE TITLE
Message Chat not working in Different region

### ISSUE THREAD

**Issue by jatinderarora90** [QuickBlox/quickblox-ios-sdk#1294] opened 2021-09-29 05:18 UTC
After implementing chat, its working in India but not in Australia..

**Comment by QB-nikolay-zolotarov** [comment] 2021-09-29 14:30
Hello @jatinderarora90 ,

This is Nikolay from QuickBlox support.

There are no complaints from other customers from Australia. 

In order to investigate the issue, please provide me with the following information:
1. Please specify what exactly is not working.
2. Are there any error messages? Please provide me with full REST + XMPP logs as an attachment in .txt format. 
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/section/14-gathering-logs-guides
)
3. Please specify if users from Australia use any VPN service.
4. Please ask users who faced this issue to run a traceroute command to api.quickblox.com and provide us with the full result. You may use this guide: [https://www.noip.com/support/knowledgebase/trace-route-guide/](https://www.noip.com/support/knowledgebase/trace-route-guide/)

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:54
@jatinderarora90 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:54 UTC
