### ISSUE TITLE
How can I get online/offline status of a member that is not my friend?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/quickblox-ios-sdk#294] opened 2016-02-15 06:57 UTC
Please help me with the question above.

**Comment by iSevenDays** [comment] 2016-02-15 10:07
Hi tranngoclinh88,

Please see http://quickblox.com/developers/SimpleSample-users-ios#Online.5COffline_status

**Comment by nikeboi89** [comment] 2016-02-16 03:05
Hi all,

I tried but I can't get other user's lastRequestAt. It is null all the time. I only can get lastRequestAt of current user. Is there other way to determine the status?

Thanks!

**Comment by Raikerian** [comment] 2016-02-18 09:11
Hi,

lastRequestedAt of user is only available if you are getting user from REST (e.g. QBRequest methods).
I have tested it and it is working as intended.

**Comment by nikeboi89** [comment] 2016-02-19 04:02
Thanks! It works. I have another question regarding this.
How can I get online users in a dialog that is a group chat? I use requestOnlineUsersWithCompletionBlock of QBChatDialog but it only returns current user's id. I also tried to get users by ID use usersWithIDs of QBRequest but lastRequestAt is null.

**Comment by Raikerian** [comment] 2016-02-22 09:42
Seems like you have created separate issue already, closing this.

**Closed by Raikerian** 2016-02-22 09:42 UTC
Labels: question
