### ISSUE TITLE
Unable to receive offline messages inside app whenever app goes to background or killed

### ISSUE THREAD

**Issue by rsbydv** [QuickBlox/quickblox-ios-sdk#1185] opened 2019-11-01 16:33 UTC
**New Issue Checklist**

 - [yes ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [yes ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 13.1                                    |                                          
Quickblox iOS SDK version      | 2.17.4                                |
Xcode Version                  |  11.1                           |
Repro with our demo sample     | yes but only sometimes when repeatedly tried. The same happens in my project too, it works fine only sometimes   |

**Steps to reproduce the behavior**
1. open app -> login -> start chat 
2. click home and send app in the background
3. send some messages from another device to the first user
4. received the chat push notification in the first device.
5. click the app icon in the first device to awake the app from the background to the foreground.
6. no messages received in the app. "didAddMessageToMemoryStorage" of QBService class doesn't get called which is normally called in the foreground state when we received the message in the foreground

**Any others comments**
Please advise how to resolve this issue.

**Comment by QB-vladyslav-vyshniak** [comment] 2019-11-05 11:53
Hello @rsbydv 

Thank you for contacting QuickBlox support.

Have you tried to reproduce the reported issue on the application which was created with the using of xCode 10? 
Could you provide me with the detailed logs? 

Looking forward to your reply.

**Comment by rsbydv** [comment] 2019-11-08 07:39
Hi, Thanks for your reply.

I can not build my application with Xcode 10 now as some of app dependencies require Xcode 11. Also, there are no logs generated at the time where we did not get any message when coming to the foreground. This is happening on both the platforms Android and iOS.

looking forward to your reply.

**Comment by QB-vladyslav-vyshniak** [comment] 2020-02-17 15:41
Hello @rsbydv 

Is the reported issue still relevant for you or could be "Closed"?

**Comment by shoaibHassanAttech** [comment] 2020-08-19 07:29
Hi,
i am sending message with this code
```
let message = QBChatMessage.markable()
        message.text = messageText
        message.dialogID = self.channelIDString
        let chatDialog = QBChatDialog(dialogID: nil, type: .private)
        message.customParameters = ["channelID" : self.channelIDString,"save_to_history":true]
        chatDialog.occupantIDs = [peerQuickbloxID]
        chatDialog.send(message) { (error) in
        }
```
but unable to recieve that message when user connect to chat and following method does't call

    `func chatDidReceive(_ message: QBChatMessage) {`

**Comment by silicus-kirankhalkar** [comment] 2020-08-25 03:59
@QB-vladyslav-vyshniak 

Could you please look on the below issue.
https://github.com/QuickBlox/quickblox-ios-sdk/issues/1231

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:41
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:41 UTC
