### ISSUE TITLE
totalEntries in QBResponsePage is zero for public group messages request

### ISSUE THREAD

**Issue by asadali737** [QuickBlox/quickblox-ios-sdk#1268] opened 2021-02-09 10:47 UTC
**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 14.2                                    |                                          
Quickblox iOS SDK version      | 2.17.5                                  |
QuickbloxWebRTC SDK version    | 2.7.4                                  |                               
Xcode Version                  | Xcode 12.2                              |

**Actual behavior**
When I get `QBRequest.messages(withDialogID:` messages it should return correct `totalEntries` in page object of success block. Right now it's coming 0

**Debug Request**

```swift
GET URL:https://api.quickblox.com/chat/Message.json?chat_dialog_id=601d8c7da0eb47532e51a602&limit=50&mark_as_read=0&sort_asc=date_sent
headers: {
    "Accept-Language" = "en;q=1";
    "QB-OS" = "iOS 14.2";
    "QB-SDK" = "iOS 2.17.9";
    "QB-Token" = 1e3a3a6029237a3f256d75928af7e2a0690159e2;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Tellum/2.1 (iPhone; iOS 14.2; Scale/3.00)";
}
parameters: {
    "chat_dialog_id" = 601d8c7da0eb47532e51a602;
    limit = 50;
    "mark_as_read" = 0;
    "sort_asc" = "date_sent";
}

```

**Steps to reproduce the behavior**
```swift

let resPage = QBResponsePage(limit: 50, skip: self.currentPageNumber*50)

let extendedRequest = ["sort_asc": "date_sent", "mark_as_read": "0"]
QBRequest.messages(withDialogID: self.chatRoomModel.quickBloxId, extendedRequest: extendedRequest, for: resPage, successBlock: { (response, messages, page) in

//            print("QBRequest.messages response: ", response)
    print("QBRequest.messages: ", messages.count)
    print("QBRequest.page: ", page.totalEntries)
    
    if self.currentPageNumber == 0 { self.chatMessages = messages }
    else { self.chatMessages.append(contentsOf: messages) }
    
    self.currentPageNumber += 1
    
    self.tblChatRoom.reloadData()
    
}, errorBlock: { (response) in
    
    print("QBRequest.messages(withDialogID Error: ", response)
})

```

**Any others comments**
In above mentioned sample code, `page.totalEntries ` is always coming `0`
Please reply soon, as its blocker issue for our application.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:59
@asadali737 The issue is being closed as outdated. 

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:59 UTC
