### ISSUE TITLE
[QBResponse], status: 422

### ISSUE THREAD

**Issue by Sudhansub** [QuickBlox/quickblox-ios-sdk#1183] opened 2019-10-22 03:37 UTC
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

My application was working fine in iOS 12. But when users are trying to open app in iOS 13 its returning "[QBResponse], status: 422" from quickblox. 

 let extendedRequest = ["sort_des" : "last_message_date_sent"]
        let page = QBResponsePage(limit: 100, skip: 0)
        
        QBRequest.dialogs(for: page, extendedRequest: extendedRequest, successBlock: { (response: QBResponse, dialogs: [QBChatDialog]?, dialogsUsersIDs: Set<NSNumber>?, page: QBResponsePage?) -> Void in

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 13.0                                    |                                          
Quickblox iOS SDK version      | 2.17.4                                  |
QuickbloxWebRTC SDK version    | 2.7                                  |                               
Xcode Version                  | e.g. Xcode 11                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by oskarko** [comment] 2019-10-26 07:41
Same issue here. It's related to iOS 13, could you fix it??? Thanks!

**Comment by QB-vladyslav-vyshniak** [comment] 2019-10-28 16:01
Hello @Sudhansub and @oskarko 

Thank you for contacting QuickBlox support.

Have you tried to use IOS SDK 2.17.4 and xCode 10? 
Currently, the developers don't recommend to use xCode 11 because it's not stable version yet, there are some bugs and issues. 

Let me know about a result using xCode 10 for implementation.

Looking forward to your reply.

**Comment by oskarko** [comment] 2019-10-28 16:02
yeah, xCode 11, that´s the problem so...

**Comment by QB-vladyslav-vyshniak** [comment] 2019-10-28 16:18
@oskarko 

So, currently you can use xCode 10, all works as expected there.

Let me know if you have any additional questions regarding this issue.

**Comment by mandeepsinghgill** [comment] 2020-01-10 13:16
As i talked to quikblox team they answered this : 

Please try to create sessions with user credentials, please check the instructions: https://quickblox.com/developers/Authentication_and_Authorization#With_User_authorization

If this help someone please let me know :) because i didn't tried or update here soon.

**Comment by QB-vladyslav-vyshniak** [comment] 2020-01-30 08:33
@oskarko last releases of xCode 11 are stable and now you can build your application using xCode 11 + IOS SDK 2.17.4.

Let me know about a result.

**Comment by QB-vladyslav-vyshniak** [comment] 2020-01-30 08:35
@mandeepsinghgill did the suggested method help you resolve the issue or it is still relevant for you?

**Comment by Patrick-foreseers** [comment] 2020-01-31 09:16
I'm using these frameworks before iOS13 and they works fine, however it fails to compile after pod update to Quickblox 2.17.4.

pod 'QuickBlox', '2.9.2'
pod 'Quickblox-WebRTC', '2.5’
pod 'QMChatViewController', ‘0.4.1.1’
pod 'QMServices', ‘0.4.5’

**Comment by QB-vladyslav-vyshniak** [comment] 2020-01-31 16:07
@Patrick-foreseers 

Proceed with the update of pod 'Quickblox-WebRTC', '2.5’ to the latest version => 2.7.4
https://cocoapods.org/pods/Quickblox-WebRTC  and let me know about a result.

**Comment by Patrick-foreseers** [comment] 2020-01-31 16:10
I'd update all the 4 frameworks but still not working.

在 2020年2月1日週六 上午12:07，Vladyslav Vyshniak <notifications@github.com> 寫道：

**Comment by Patrick-foreseers** [comment] 2020-02-03 02:59
> @Patrick-foreseers
> 
> Proceed with the update of pod 'Quickblox-WebRTC', '2.5’ to the latest version => 2.7.4
> https://cocoapods.org/pods/Quickblox-WebRTC and let me know about a result.

**pod 'Quickblox-WebRTC', '2.7.4'**
[!] CocoaPods could not find compatible versions for pod "Quickblox-WebRTC":
  In Podfile:
    Quickblox-WebRTC (= 2.7.4)

Specs satisfying the `Quickblox-WebRTC (= 2.7.4)` dependency were found, but they required a higher minimum deployment target.


**https://cocoapods.org/pods/Quickblox-WebRTC**
HTTP ERROR 503

**Before update QMServices, 2 errors were found.**
/Pods/QMServices/QMChatCache/QMChatCache/CoreData/Entries/CDAttachment.m:11: Property 'data' not found on object of type 'QBChatAttachment *'

**After update QMServices, 20 errors were found.**
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:17:31: error: unknown type name 'AVAsset'
@property (strong ,nonatomic) AVAsset *asset;
                              ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:17:1: error: property with 'retain (or strong)' attribute must be of object type
@property (strong ,nonatomic) AVAsset *asset;
^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:21:31: error: unknown type name 'AVAssetImageGenerator'
@property (strong, nonatomic) AVAssetImageGenerator *imageGenerator;
                              ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:21:1: error: property with 'retain (or strong)' attribute must be of object type
@property (strong, nonatomic) AVAssetImageGenerator *imageGenerator;
^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:37:4: error: expected a type
- (AVAsset *)asset {
   ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:127:37: error: expected a type
- (void)generateThumbnailFromAsset:(AVAsset *)thumbnailAsset withSize:(CGSize)size
                                    ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:166:23: error: expected a type
- (void)prepareAsset:(AVAsset *)asset {
                      ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:39:9: error: use of undeclared identifier '_asset'
    if (_asset == nil) {
        ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:41:35: error: use of undeclared identifier 'AVURLAssetPreferPreciseDurationAndTimingKey'
        NSDictionary *options = @{AVURLAssetPreferPreciseDurationAndTimingKey : @YES};
                                  ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:42:9: error: use of undeclared identifier '_asset'
        _asset = [[AVURLAsset alloc] initWithURL:_assetURL
        ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:42:20: error: use of undeclared identifier 'AVURLAsset'
        _asset = [[AVURLAsset alloc] initWithURL:_assetURL
                   ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:46:12: error: use of undeclared identifier '_asset'
    return _asset;
           ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:102:9: error: use of undeclared identifier 'AVAsset'
        AVAsset *asset = strongSelf.asset;
        ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:102:18: error: use of undeclared identifier 'asset'
        AVAsset *asset = strongSelf.asset;
                 ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:111:13: error: use of undeclared identifier 'AVKeyValueStatus'
            AVKeyValueStatus keyStatus = [asset statusOfValueForKey:key error:&error];
            ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:112:17: error: use of undeclared identifier 'keyStatus'
            if (keyStatus == AVKeyValueStatusFailed) {
                ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:112:30: error: use of undeclared identifier 'AVKeyValueStatusFailed'
            if (keyStatus == AVKeyValueStatusFailed) {
                             ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:122:34: error: use of undeclared identifier 'asset'
        [strongSelf prepareAsset:asset];
                                 ^
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:99:6: error: bad receiver type 'int *'
    [self.asset loadValuesAsynchronouslyForKeys:requestedKeys completionHandler:^{
     ^~~~~~~~~~
/Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:103:40: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
        QMSLog(@"3 Completed Load %@", _messageID);

**Comment by Patrick-foreseers** [comment] 2020-02-03 07:43
> > @Patrick-foreseers
> > Proceed with the update of pod 'Quickblox-WebRTC', '2.5’ to the latest version => 2.7.4
> > https://cocoapods.org/pods/Quickblox-WebRTC and let me know about a result.
> 
> **pod 'Quickblox-WebRTC', '2.7.4'**
> [!] CocoaPods could not find compatible versions for pod "Quickblox-WebRTC":
> In Podfile:
> Quickblox-WebRTC (= 2.7.4)
> 
> Specs satisfying the `Quickblox-WebRTC (= 2.7.4)` dependency were found, but they required a higher minimum deployment target.
> 
> **https://cocoapods.org/pods/Quickblox-WebRTC**
> HTTP ERROR 503
> 
> **Before update QMServices, 2 errors were found.**
> /Pods/QMServices/QMChatCache/QMChatCache/CoreData/Entries/CDAttachment.m:11: Property 'data' not found on object of type 'QBChatAttachment *'
> 
> **After update QMServices, 20 errors were found.**
> /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:17:31: error: unknown type name 'AVAsset'
> @Property (strong ,nonatomic) AVAsset *asset;
> ^
> /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:17:1: error: property with 'retain (or strong)' attribute must be of object type
> @Property (strong ,nonatomic) AVAsset *asset;
> ^
> /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:21:31: error: unknown type name 'AVAssetImageGenerator'
> @Property (strong, nonatomic) AVAssetImageGenerator *imageGenerator;
> ^
> /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:21:1: error: property with 'retain (or strong)' attribute must be of object type
> @Property (strong, nonatomic) AVAssetImageGenerator *imageGenerator;
> ^
> /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:37:4: error: expected a type
> 
> * (AVAsset *)asset {
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:127:37: error: expected a type
> * (void)generateThumbnailFromAsset:(AVAsset *)thumbnailAsset withSize:(CGSize)size
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:166:23: error: expected a type
> * (void)prepareAsset:(AVAsset *)asset {
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:39:9: error: use of undeclared identifier '_asset'
>   if (_asset == nil) {
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:41:35: error: use of undeclared identifier 'AVURLAssetPreferPreciseDurationAndTimingKey'
>   NSDictionary *options = @{AVURLAssetPreferPreciseDurationAndTimingKey : @yES};
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:42:9: error: use of undeclared identifier '_asset'
>   _asset = [[AVURLAsset alloc] initWithURL:_assetURL
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:42:20: error: use of undeclared identifier 'AVURLAsset'
>   _asset = [[AVURLAsset alloc] initWithURL:_assetURL
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:46:12: error: use of undeclared identifier '_asset'
>   return _asset;
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:102:9: error: use of undeclared identifier 'AVAsset'
>   AVAsset *asset = strongSelf.asset;
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:102:18: error: use of undeclared identifier 'asset'
>   AVAsset *asset = strongSelf.asset;
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:111:13: error: use of undeclared identifier 'AVKeyValueStatus'
>   AVKeyValueStatus keyStatus = [asset statusOfValueForKey:key error:&error];
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:112:17: error: use of undeclared identifier 'keyStatus'
>   if (keyStatus == AVKeyValueStatusFailed) {
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:112:30: error: use of undeclared identifier 'AVKeyValueStatusFailed'
>   if (keyStatus == AVKeyValueStatusFailed) {
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:122:34: error: use of undeclared identifier 'asset'
>   [strongSelf prepareAsset:asset];
>   ^
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:99:6: error: bad receiver type 'int *'
>   [self.asset loadValuesAsynchronouslyForKeys:requestedKeys completionHandler:^{
>   ^~~~~~~~~~
>   /Pods/QMServices/QMChatService/QMChatService/QMAttachmentService/QMAttachmentAssetService/QMAssetLoader.m:103:40: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
>   QMSLog(@"3 Completed Load %@", _messageID);

**The versions which are updated from Pods.**
Installing QMChatViewController 0.5.1 (was 0.4.1.1 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing QMServices 0.5.5 (was 0.4.5 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing QuickBlox 2.17.4 (was 2.9.2 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing Quickblox-WebRTC 2.6.3 (was 2.5 and source changed to `https://cdn.cocoapods.org/` from `trunk`)

**Comment by Patrick-foreseers** [comment] 2020-02-12 03:01
> @Patrick-foreseers
> 
> Proceed with the update of pod 'Quickblox-WebRTC', '2.5’ to the latest version => 2.7.4
> https://cocoapods.org/pods/Quickblox-WebRTC and let me know about a result.
any idea?

**Comment by QB-vladyslav-vyshniak** [comment] 2020-02-17 15:56
@Patrick-foreseers 

We are checking the provided logs. 
I let you know once we will have any update for you.

**Comment by samratpramanik** [comment] 2020-04-03 15:59
The same issue happened to me. I cannot make log-in or sign up when the application run in Xcode 11.2.1.  And the worst part is Apple did not support AppStore build from starting of April 2020. 

           error: Request failed: client error (422)
           reasons: {
                  errors =     {
                        base =         (
                              "Unexpected signature"
                        );
                  };
             }

Please fix this issue as soon as possible.  Thanks!

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:40
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:40 UTC
