### ISSUE TITLE
Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.

### ISSUE THREAD

**Issue by Rushang007** [QuickBlox/quickblox-ios-sdk#1201] opened 2020-04-11 12:31 UTC
i'm facing this error in iOS 13 & Xcode 11.4 
i'm using latest version of Quickblox and webrtc SDK

can you please help ?
![WhatsApp Image 2020-04-08 at 7 42 53 PM](https://user-images.githubusercontent.com/16713953/79043703-63982580-7c1e-11ea-8be4-6055b60d6d78.jpeg)

**Comment by duynk163** [comment] 2020-04-22 08:22
You can try with objective-C, it's OK with me.

**Comment by Rushang007** [comment] 2020-04-22 08:37
@duynk163 what do you mean by objective-C, can you explain in details how to use in my swift code?

**Comment by Awais987** [comment] 2020-04-23 19:01
@Rushang007  i am also facing this issue after installing latest quickblox webrtc swift sdk?? Do you find any solution related to this

**Comment by katafo** [comment] 2020-04-24 13:50
> "On iOS 13.0 and later, if you fail to report a call to CallKit, the system will terminate your app. Repeatedly failing to report calls may cause the system to stop delivering any more VoIP push notifications to your app. If you want to initiate a VoIP call without using CallKit, register for push notifications using the UserNotifications framework instead of PushKit."


https://developer.apple.com/documentation/pushkit/pkpushregistrydelegate/2875784-pushregistry

You must report incoming call immediately in **didReceiveIncomingPushWith**. Example:

```
func pushRegistry(_ registry: PKPushRegistry, didReceiveIncomingPushWith payload: PKPushPayload, for type: PKPushType, completion: @escaping () -> Void) {
      
        let update = CXCallUpdate()
        update.remoteHandle = CXHandle(type: .phoneNumber, value: '')

        provider.reportNewIncomingCall(with: uuid, update: update) { error in
            ....
        }
   }
```

**Comment by VladimirNybozhinsky** [comment] 2020-04-29 16:53
Please check the latest update Swift-Video-Chat-WEBRTC
https://github.com/QuickBlox/quickblox-ios-sdk/commit/9b70536f44558d7ce004449731a9cfb4e539ea2b

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:43
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed** 2023-01-12 10:47 UTC
