### ISSUE TITLE
Incoming video/audio call not working in background (Swift, iOS 13)

### ISSUE THREAD

**Issue by Rushang007** [QuickBlox/quickblox-ios-sdk#1199] opened 2020-04-04 08:55 UTC
iOS Version  - 13.0                                            
Quickblox iOS SDK version   - 2.17.4
QuickbloxWebRTC SDK version -   2.7.4
Xcode Version  - 11.2.0

please help 

Thanks in Advance

**Comment by VladimirNybozhinsky** [comment] 2020-04-29 16:53
Please check the latest update Swift-Video-Chat-WEBRTC
https://github.com/QuickBlox/quickblox-ios-sdk/commit/9b70536f44558d7ce004449731a9cfb4e539ea2b

**Comment by virajptridhya** [comment] 2020-06-24 10:20
@Rushang007  I am facing the same issue with iOS 13. Incoming video call not working in background.

**Comment by parthsit** [comment] 2020-06-24 11:26
Hello @Rushang007 I am also facing same issue for incoming video call in iOS 13, It is working fine in iOS 12. I have mentioned information below which I am getting in iOS 13. Did you able to find any solution related to this ?

"didReceiveIncomingPushWith called"
" timeIntervalSinceStartCall > QBRTCConfig.answerTimeInterval"
2020-06-23 22:51:12.114253+0530[2555:1050373] Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:]
 without delay.
2020-06-23 22:51:12.114529+0530[2555:1050373] *** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-36/PKPushRegistry.m:343
2020-06-23 22:51:12.127602+0530[2555:1050373] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:43
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:43 UTC
