### ISSUE TITLE
Some microphone or voice issues in latest sample WebRtc Swift

### ISSUE THREAD

**Issue by Awais987** [QuickBlox/quickblox-ios-sdk#1209] opened 2020-04-29 19:56 UTC
**New Issue Checklist**

 - [yes] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [yes] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 13.4.1                                    |                                          
Quickblox iOS SDK version      | e.g. 2.17.4                                  |
QuickbloxWebRTC SDK version    | e.g. 2.7.4                                  |                               
Xcode Version                  | e.g. Xcode 11.4.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   | yes

**Did this work before?**
           

**Expected behavior**

**Actual behavior**

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

**Any others comments**

**Comment by Muhammad7861** [comment] 2020-04-30 20:52
I have also this issue same 
when app in terminate, iphone locked and some time in background microphone issue occured some time 
I request to quickblox test swift webrtc app thoroughly 
On the other hand objective c app wokring fine.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:46
@Muhammad7861 @Awais987 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:46 UTC
