### ISSUE TITLE
Session is nil if hangup call imediately after creating new session causing issue on other peer.

### ISSUE THREAD

**Issue by shoaibhassan1** [QuickBlox/quickblox-ios-sdk#1230] opened 2020-08-18 05:28 UTC
If Peer 1 create a new call session and showing outgoing call screen with hangup option after sending VOIP notification on other peer,and hagup call immediately then peer 2 is showing callkit because app is killede and accept then call, but peer 2 is still not connected to chat and press accept button, then is stucked on call screen and no function from both of this will be call on peer 2 side on completion of connecting to chat.

```
func didReceiveNewSession(_ session: QBRTCSession, userInfo: [String : String]? = nil)
    {}
```
```
func session(_ session: QBRTCSession, hungUpByUser userID: NSNumber, userInfo: [String : String]? = nil) {
}
```

So peer 2 is stucked as none of delegate method gets called because session is ended at peer 1 side.
Please help me in this case.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:49
@shoaibhassan1 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:49 UTC
