### ISSUE TITLE
Not able to hear with Bluetooth handset

### ISSUE THREAD

**Issue by devgeektech** [QuickBlox/quickblox-ios-sdk#1210] opened 2020-05-04 18:55 UTC
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 13.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.17.4                                 |
QuickbloxWebRTC SDK version    | e.g. 2.7.4                                  |                               
Xcode Version                  | e.g. Xcode 11.3                              |

Hello 

I am trying to implement Quickblox webrtc for video call but I am not able to configure Bluetooth handset.  

this is the code I have implemented for bluetooth as per the documentation. 
```

if audioSession.isInitialized == false {
            audioSession.initialize { configuration in
                // adding blutetooth support
               
                configuration.categoryOptions.insert(AVAudioSession.CategoryOptions.allowBluetooth)
                configuration.categoryOptions.insert(AVAudioSession.CategoryOptions.allowBluetoothA2DP)
                // adding airplay support
                configuration.categoryOptions.insert(AVAudioSession.CategoryOptions.allowAirPlay)
                if session.conferenceType == .video {
                    // setting mode to video chat to enable airplay audio and speaker only
                    configuration.mode = AVAudioSession.Mode.videoChat.rawValue
                }
            }
        }

```
Please help with this issue

**Comment by tmkinger** [comment] 2020-07-07 16:16
I have the same issue, and even I'm using the latest versions of iOS SDK and WebRTC SDK.

**Comment by maughray** [comment] 2021-07-05 11:57
I also have the same issue

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:46
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:46 UTC
