### ISSUE TITLE
Can not make audio call once app in background or terminated state.

### ISSUE THREAD

**Issue by vishalrana-spaceo** [QuickBlox/quickblox-ios-sdk#1194] opened 2020-03-25 04:36 UTC
**New Issue Checklist**

 - [ yes] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ yes] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 13.3.1                                    |                                          
Quickblox iOS SDK version      | e.g. 2.17.4                                 |
QuickbloxWebRTC SDK version    | e.g. 2.7.4                                 |                               
Xcode Version                  | e.g. Xcode 11.3.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |
yes
**Did this work before?**
it is working on iOS 12. but same code stopped working on iOS 13.0 and above.

**Expected behavior**
call kit should shown if app is in background or terminated.

**Actual behavior**
Apps is crashing..

Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.

**Logs**

2020-03-24 17:32:03.950519+0530 sample-videochat-webrtc-swift[10480:769062] Apps receving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as   pushRegistry:didReceiveIncomingPushWithPayload:forType:[withCompletionHandler:] without delay.
2020-03-24 17:32:03.950994+0530 sample-videochat-webrtc-swift[10480:769583] [ChatService]: Connecting with JID: 104796132-79563@chat.quickblox.com/A6F1F55A-A2AB-4EE3-BA23-650CC20CF879
2020-03-24 17:32:03.951693+0530 sample-videochat-webrtc-swift[10480:769062] *** Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-37/PKPushRegistry.m:343
2020-03-24 17:32:03.952616+0530 sample-videochat-webrtc-swift[10480:769062] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push callback.'
*** First throw call stack:
(0x19bec2a48 0x19bbe9fa4 0x19bdc4e88 0x19c1fa654 0x1afc06a5c 0x104bfebd8 0x104c0d858 0x1afc059cc 0x104bfd7fc 0x104bfebd8 0x104c0cc34 0x19be405e4 0x19be3b5d8 0x19be3aadc 0x1a5ddb328 0x19ff4863c 0x1001129e0 0x19bcc4360)
libc++abi.dylib: terminating with uncaught exception of type NSException

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];



issue is coming on iOS 13.0 and after

**Comment by vishalrana-spaceo** [comment] 2020-03-31 11:29
Hello devs,

Any update on issue??

Thanks

**Comment by Muhammad7861** [comment] 2020-04-30 20:55
background call issue now resolved in new sdk but some issues are pending for mic in background, terminated or iphone locked state 
quickblox team is very slow in response.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:41
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:41 UTC
