### ISSUE TITLE
Pods updates to QuickBlox 2.7 issue.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#370] opened 2016-03-30 15:35 UTC
Hey guys, just tried to update via cocoa pods to a new version. Here is an error. Can you help. Thanks one more time!!!!!!

> pod 'QMChatViewController', '~> 0.3.5'
> pod 'QMServices', '~> 0.3.8'
> pod 'QuickBlox', '~> 2.7'

> [!] Unable to satisfy the following requirements:
> 
> - `QuickBlox (~> 2.0)` required by `QMChatViewController (0.3.5)`
> - `QuickBlox (~> 2.0)` required by `QMChatViewController/Utils (0.3.5)`
> - `QuickBlox (~> 2.0)` required by `QMChatViewController/Sections (0.3.5)`
> - `QuickBlox (~> 2.0)` required by `QMChatViewController/Categories (0.3.5)`
> - `QuickBlox (~> 2.0)` required by `QMChatViewController/KeyboardViewController (0.3.5)`
> - `QuickBlox (~> 2.0)` required by `QMChatViewController/Protocols (0.3.5)`
> - `QuickBlox (~> 2.0)` required by `QMChatViewController/Views (0.3.5)`
> - `QuickBlox (~> 2.6.5)` required by `QMServices (0.3.8)`
> - `QuickBlox (~> 2.7)` required by `Podfile`

**Comment by matrosovDev** [comment] 2016-03-30 16:34
Also if I leave this lines as:

> pod 'QMChatViewController'
> pod 'QMServices'
> pod 'QuickBlox'

it upload for me no the last version as I suppose:

> Using QMChatViewController (0.2.5)
> Using QMServices (0.3.7)
> Using QuickBlox (2.6.6)

Cocoa Pods version is 0.34.4

**Comment by matrosovDev** [comment] 2016-03-30 16:49
what actually strange pod install works time to time =)

**Comment by coredream** [comment] 2016-03-30 17:25
Same issue here.  Seems like it's impossible to install QuickBlox 2.7 AND the latest QMServices (0.3.8).

I think the issue is due to the semver constraint:

https://github.com/CocoaPods/Specs/blob/master/Specs/QMServices/0.3.8/QMServices.podspec.json#L38

I believe the "~> 2.6.5" does not match on 2.7.  I think skipping the patch number (3rd digit) in some of your releases is also adding to the confusion.

**Comment by Raikerian** [comment] 2016-03-31 08:24
Hi @matrosovDev and @coredream 

Thank you for reporting the issue, I was able to reproduce and fix it.
We are planning to make a release in the next weeks, so, there is a temporary fix for you right now:

1) Place a QMServices.podspec file in your project folder with this content:
```
#
#  Be sure to run `pod spec lint QMServices.podspec --verbose --use-libraries --allow-warnings' to ensure this is a
#  valid spec and to remove all comments including this before submitting the spec.
#
#  To learn more about Podspec attributes see http://docs.cocoapods.org/specification.html
#  To see working Podspecs in the CocoaPods repo see https://github.com/CocoaPods/Specs/
#   
#  To submit use `pod trunk push QMServices.podspec --verbose --use-libraries --allow-warnings`
#


Pod::Spec.new do |s|
  s.name         = "QMServices"
  s.version      = "0.3.8"
  s.summary      = "Easy-to-use services for Quickblox SDK, for speeding up development of iOS chat applications."
  s.homepage     = "https://github.com/QuickBlox/q-municate-services-ios"
  s.license      = { :type => 'BSD', :file => '../LICENSE.txt' }
  s.authors      = {"Anton Sokolchenko" => "anton.sokolchenko@quickblox.com", "Andrey Ivanov" => "andrey.ivanov@quickblox.com", "Vitaliy Gorbachov" => "vitaliy.gorbachov@quickblox.com"}
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/QuickBlox/q-municate-services-ios.git", :tag => "#{s.version}"}
  s.source_files  = "Classes", "**/*.{h,m}"
  s.exclude_files = "Pods"
  s.frameworks = "CoreData"
  s.requires_arc = true
  s.xcconfig = { "FRAMEWORK_SEARCH_PATHS" => "$(PODS_ROOT)/QuickBlox/" }
  s.prefix_header_contents = 
  '#import <Quickblox/Quickblox.h>
#import <CoreData/CoreData.h>
#import <Quickblox/QBMulticastDelegate.h>
#import <Bolts/Bolts.h>'
  s.resource_bundle = {'QMChatCacheModel' => 'QMChatCache/QMChatCache/CoreData/QMChatServiceModel.xcdatamodeld', 'QMContactListCacheModel' => 'QMContactListCache/QMContactListCache/CoreData/QMContactListModel.xcdatamodeld', 'QMUsersCacheModel' => 'QMUsersCache/QMUsersCache/CoreData/QMUsersModel.xcdatamodeld'}

  s.dependency "QuickBlox", ">= 2.6.5"
  s.dependency "Bolts",  '>= 1.5.0'
end
```
2) Modify your Podfile, and make QMServices to look into this podspec. Here how it should look now:
```
pod 'QMChatViewController'
pod 'QMServices', :podspec => 'QMServices.podspec'
pod 'QuickBlox'
```

3) Perform `pod update` or (if doesn't work) remove Podfile.lock file, Pods folder and .xcworkspace file and perform a complete `pod install`.

Here you go, let me know if it works for you.

**Comment by coredream** [comment] 2016-03-31 15:01
Thanks @Raikerian, temp fix works for me.  I get a warning about the license, but still installs successfully.

`[!]` Unable to read the license file `/myProject/Pods/LICENSE.txt` for the spec `QMServices (0.3.8)`

**Comment by Raikerian** [comment] 2016-03-31 16:44
@coredream you can ignore that warning for now, everything will be ok

**Comment by matrosovDev** [comment] 2016-04-05 08:46
Hey guys, do you have any news regarding this pod issue. I know you said you plan to make a release during the week or so. Thanks!!!

**Comment by Raikerian** [comment] 2016-04-05 14:07
Hi @matrosovDev 

As I have mentioned we are planning release in a next week. Our SDK is currently in testing state. Unfortunately I cannot give you any specific ETA for this. Please use custom podspec mentioned in this issue, it will fix the issue for you for now.
I'll let you guys know when the fix for this issue will be live.

**Comment by matrosovDev** [comment] 2016-04-13 13:17
hey guys sorry for pushing you one more time, but have you chance to update it on your side, just want to make sure that we can make it this week, maybe then it's better solution (just for now) use your workaround. thanks!!!

**Comment by Raikerian** [comment] 2016-04-13 14:23
We have plans to push release on Friday.

**Comment by Raikerian** [comment] 2016-04-15 17:20
Fixed in a latest QMServices and QMChatViewController.

**Closed by Raikerian** 2016-04-15 17:20 UTC
Labels: bug
