### ISSUE TITLE
Too many occupants for Private Dialog.

### ISSUE THREAD

**Issue by jeetrajput01** [QuickBlox/quickblox-ios-sdk#1281] opened 2021-05-20 12:35 UTC
ERROR occur while creating private chat dialog 
  Optional(
   Error reasons:{
    errors =     (
        "Too many occupants for Private Dialog."
    );
})
I found this is an error from QBResponse.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:56
@jeetrajput01 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:56 UTC
