### ISSUE TITLE
Crash if we change app name or display name

### ISSUE THREAD

**Issue by shoaibhassan1** [QuickBlox/quickblox-ios-sdk#1216] opened 2020-05-21 08:07 UTC
There is crash for key-value coding of login button  if we change app name or display name from project settings.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:51
@shoaibhassan1 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:51 UTC
