### ISSUE TITLE
response [QBResponse], status: 201 after sending message

### ISSUE THREAD

**Issue by aju10** [QuickBlox/quickblox-ios-sdk#1279] opened 2021-04-30 12:23 UTC
after sending message got this response [QBResponse], status: 201, 
and notification not send to next user
Please help me out to solve this

**Comment by aju10** [comment] 2021-05-14 12:38
@stephanoparaskeva Thanks, just join the QB Community on slack

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:57
@aju10 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:57 UTC
