### ISSUE TITLE
run sample crash

### ISSUE THREAD

**Issue by liuf1986** [QuickBlox/quickblox-ios-sdk#587] opened 2016-08-26 08:23 UTC
dyld: Library not loaded: @rpath/Quickblox.framework/Quickblox
  Referenced from: /var/containers/Bundle/Application/C202899C-CBFB-415F-B47A-DA4F7D7B4BEB/sample-videochat-webrtc.app/sample-videochat-webrtc
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/C202899C-CBFB-415F-B47A-DA4F7D7B4BEB/sample-videochat-webrtc.app/Frameworks/Quickblox.framework/Quickblox: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/C202899C-CBFB-415F-B47A-DA4F7D7B4BEB/sample-videochat-webrtc.app/Frameworks/Quickblox.framework/Quickblox'

**Comment by VitaliyGuru** [comment] 2016-08-30 13:03
@liuf1986 
Did you face with this error only on the real device or in the simulator too?

You can try these [answers](http://stackoverflow.com/questions/32730312/reason-no-suitable-image-found). 
Looking forward to hear from you about results.

**Comment by liuf1986** [comment] 2016-08-31 01:27
the real device,i try your link

**Comment by williamtran1988** [comment] 2016-09-12 09:48
I am facing this problem also. somebody can help?

**Comment by VitaliyGuru** [comment] 2016-09-12 09:49
@williamtran1988  Have you try my suggested decision ?

**Comment by VitaliyGuru** [comment] 2016-09-12 09:50
@liuf1986 Any updates?

**Comment by williamtran1988** [comment] 2016-09-12 10:06
I tried with your suggestion. But it does not help.

**Comment by Pro100Andrey** [comment] 2016-09-12 10:20
Hi @williamtran1988. For dynamic framework add Quickblox as Embedded binary:
![800px-embeddedbinary](https://cloud.githubusercontent.com/assets/1109916/18432621/a25dbca6-78eb-11e6-9d46-21ba0bbe64ad.png)

**Comment by williamtran1988** [comment] 2016-09-12 10:20
It's weird when i can get success by building application with Developer profile. Are there any different between Distribution and Developer profile?

**Comment by williamtran1988** [comment] 2016-09-13 06:16
Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: @rpath/Quickblox.framework/Quickblox
  Referenced from: /var/containers/Bundle/Application/6D5D92B0-F857-43BC-A716-EDF7C4C23D76/DEMO.app/DEMO
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/6D5D92B0-F857-43BC-A716-EDF7C4C23D76/DEMO.app/Frameworks/Quickblox.framework/Quickblox: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/6D5D92B0-F857-43BC-A716-EDF7C4C23D76/DEMO.app/Frameworks/Quickblox.framework/Quickblox'
  Dyld Version: 390.7

**Comment by Pro100Andrey** [comment] 2016-10-07 12:03
Hi @williamtran1988, please check last version of SDK

**Comment by Pro100Andrey** [comment] 2016-10-11 11:34
@williamtran1988 Any updates?

**Comment by williamtran1988** [comment] 2016-10-13 08:07
sorry for delay answer.

The issue is resolved by using cocoa pod. but i still could not add framework to project manually.

I followed all the steps you mentioned above:
1. add framework.
2.Embebed framework.
3.Clean project
...

**Comment by williamtran1988** [comment] 2016-10-13 08:54
By the way, i have the same issue when i deploy "sample-videochat-webrtc" to real device.

**Closed** 2016-10-25 08:01 UTC
Labels: question
