### ISSUE TITLE
Cant accept Video call in iOS when called from Android 

### ISSUE THREAD

**Issue by ayushhgoyal** [QuickBlox/quickblox-ios-sdk#75] opened 2015-05-28 09:12 UTC
We are having trouble in accepting call on iOS when call is initiated from Android end and same issue when call is initiated from iOS and being accepted at Android. 

We can call/receive from other combinations of platforms i.e ANdroid, iOS and Web but when trying call between Android and iOS..app tends to crash. 

Below are the iOS logs when call is being accepted that initiated from Android: 

2015-05-23 17:04:42.827 QBRTCChatSample[32844:2422793] -[QBChat loginWithUser:resource:] -> Connecting to Chat, host: chat.quickblox.com, user JID: 3200945-23057@chat.quickblox.com/24195311-EE66-47BA-A976-5B03558C3B67
2015-05-23 17:04:44.874 QBRTCChatSample[32844:2422798] QBChat/DidConnect
2015-05-23 17:04:47.257 QBRTCChatSample[32844:2422794] -[QBChat xmppStreamDidAuthenticate:] -> user: 3200945, supportsStartTLS: 1
2015-05-23 17:04:47.540 QBRTCChatSample[32844:2422816] -[QBChat xmppStream:didSendPresence:] -> Presence SNT: <presence></presence>
2015-05-23 17:04:47.541 QBRTCChatSample[32844:2422816] -[QBChat xmppStream:didSendIQ:] -> IQ SNT: <iq type="get" id="561006823"><query xmlns="jabber:iq:roster"></query></iq>
2015-05-23 17:04:47.806 QBRTCChatSample[32844:2422816] -[QBChat xmppStream:didReceivePresence:] -> Presence RCV: <presence xmlns="jabber:client" from="3200945-23057@chat.quickblox.com/24195311-EE66-47BA-A976-5B03558C3B67" to="3200945-23057@chat.quickblox.com"></presence>
2015-05-23 17:04:48.158 QBRTCChatSample[32844:2422798] -[QBChat xmppStream:didReceiveIQ:] -> IQ RCV: <iq xmlns="jabber:client" to="3200945-23057@chat.quickblox.com/24195311-EE66-47BA-A976-5B03558C3B67" type="result" id="561006823"><query xmlns="jabber:iq:roster"></query></iq>
2015-05-23 17:04:57.454 QBRTCChatSample[32844:2422850] Audio session route change reason: Override
2015-05-23 17:04:57.846 QBRTCChatSample[32844:2422068] Port Description:Receiver Switch to speaker
2015-05-23 17:04:57.927 QBRTCChatSample[32844:2422850] Audio session route change reason: Override
2015-05-23 17:05:02.209 QBRTCChatSample[32844:2422838] Renegotiation needed. userID - 3200941
2015-05-23 17:05:04.615 QBRTCChatSample[32844:2422838] Signaling state change: Have Remote Offer, userID - 3200941
2015-05-23 17:05:04.672 QBRTCChatSample[32844:2422838] Signaling state change: Stable, userID - 3200941
2015-05-23 17:05:04.924 QBRTCChatSample[32844:2422850] Audio session route change reason: Override
2015-05-23 17:05:05.193 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:05.194 QBRTCChatSample[32844:2422068] Dropped sample buffer.

2015-05-23 17:05:05.583 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:05.602 QBRTCChatSample[32844:2422838] Ice Gathering change: Gathering, userID - 3200941
2015-05-23 17:05:05.603 QBRTCChatSample[32844:2422838] Ice Gathering change: Gathering, userID - 3200941
2015-05-23 17:05:05.683 QBRTCChatSample[32844:2422068] Connection state: userID - 3200941 changed: [Checking]
2015-05-23 17:05:05.757 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:05.758 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:05.759 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:05.761 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:05.841 QBRTCChatSample[32844:2422793] -[QBChat xmppStream:didSendMessage:] -> Message SNT: <message id="1912343817" type="headline" to="3200941-23057@chat.quickblox.com" from="3200945-23057@chat.quickblox.com"><extraParams xmlns="jabber:client"><callType>1</callType><sdp>v=0
o=- 5830596617447698491 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS ARDAMS
m=audio 9 RTP/SAVPF 103 111 9 102 0 8 106 105 13 127 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:wQfmEX8/hgRv4z5l
a=ice-pwd:rTjwAKGa3HHywR+6HxdhtTdY
a=fingerprint:sha-256 FC:36:C7:54:28:FA:8F:4C:D4:76:C0:52:8D:EF:DC:CE:68:2E:94:C2:75:A0:21:5B:5E:9C:DA:A9:8A:D4:8F:41
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:103 ISAC/16000
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:127 red/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:775258713 cname:K7i2tT060r1WCg7B
a=ssrc:775258713 msid:ARDAMS ARDAMSa0
a=ssrc:775258713 mslabel:ARDAMS
a=ssrc:775258713 label:ARDAMSa0
m=video 9 RTP/SAVPF 100 116 117 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:wQfmEX8/hgRv4z5l
a=ice-pwd:rTjwAKGa3HHywR+6HxdhtTdY
a=fingerprint:sha-256 FC:36:C7:54:28:FA:8F:4C:D4:76:C0:52:8D:EF:DC:CE:68:2E:94:C2:75:A0:21:5B:5E:9C:DA:A9:8A:D4:8F:41
a=setup:active
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 1249833884 3278979412
a=ssrc:1249833884 cname:K7i2tT060r1WCg7B
a=ssrc:1249833884 msid:ARDAMS ARDAMSv0
a=ssrc:1249833884 mslabel:ARDAMS
a=ssrc:1249833884 label:ARDAMSv0
a=ssrc:3278979412 cname:K7i2tT060r1WCg7B
a=ssrc:3278979412 msid:ARDAMS ARDAMSv0
a=ssrc:3278979412 mslabel:ARDAMS
a=ssrc:3278979412 label:ARDAMSv0
</sdp><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><sessionID>f1b929ba-581c-45c3-9824-b7399c4caa1e</sessionID><callerID>3200941</callerID><platform>ios</platform><signalType>accept</signalType><userInfo><accept>hello</accept></userInfo><opponentsIDs><opponentID>3200945</opponentID></opponentsIDs></extraParams></message>
2015-05-23 17:05:06.429 QBRTCChatSample[32844:2422838] Ice Gathering change: Complete, userID - 3200941
WARNING: no real random source present!
2015-05-23 17:05:06.511 QBRTCChatSample[32844:2422068] Connection state: userID - 3200941 changed: [Connected]
2015-05-23 17:05:59.704 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:59.705 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05-23 17:05:59.706 QBRTCChatSample[32844:2422068] Dropped sample buffer.
2015-05

**Comment by enginegl** [comment] 2015-05-29 13:56
+1

**Comment by hellc** [comment] 2015-05-29 14:04
I faced with a same problem. I think the problem is with WebRTC module and relates with ARM arch. devices. I think here is no problem with ARM64 devices. Here is the bug information image.
![screen shot 2015-05-29 at 17 01 22](https://cloud.githubusercontent.com/assets/750178/7884135/67af2fa8-0624-11e5-819c-573cee763f04.png)

**Comment by Pro100Andrey** [comment] 2015-06-02 08:19
What version of sdk do you use ?

**Comment by hellc** [comment] 2015-06-02 09:45
Using QuickBlox (2.2.4)
Using Quickblox-WebRTC (1.0.4)

Got it from cocoapods

**Comment by enginegl** [comment] 2015-06-03 11:55
@Pro100Andrey, you can reproduce this issue with QB WebRTC samples for Android & iOS.

**Comment by apurvasaxena** [comment] 2015-06-08 12:30
using quickblox- videochat-webrtc
sdk version: 2.2.3
gradleVersion: 2.3

**Comment by Pro100Andrey** [comment] 2015-06-09 09:45
@enginegl yes, I reproduced, now we are resolving this problem

**Comment by hellc** [comment] 2015-06-15 13:54
@Pro100Andrey есть успехи?

**Comment by Pro100Andrey** [comment] 2015-06-16 09:23
Fixed in 1.0.5

**Closed by Pro100Andrey** 2015-06-16 09:23 UTC

**Comment by negawoldia** [comment] 2015-10-26 14:50
Hey,
I have a unique problem. I get video call request from ios to android. The android responds with acceptCall, However, my session.acceptCall(userInfo) is not recieved by the ios.
ioS to iOs works fine. From Android to ios also works fine.
Thanks,

**Comment by s612** [comment] 2016-03-17 09:51
Hi, when i hangs up a session. I am unable to start the new call. But once I terminate the app I can start my call.What could be the reason?
