### ISSUE TITLE
QBCBlob use ID instead of UID in QBChatAttachment

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/quickblox-ios-sdk#823] opened 2017-06-18 12:35 UTC
**Environment details**
IOS 10 and above 
`- QMServices (0.4.5):
    - Bolts (>= 1.5.0)
    - QuickBlox (>= 2.6.5)
    - QuickBlox (2.9.2)
`
**Did this work before?**
YES

**Description**

`

         [QBRequest TUploadFile:imageData fileName:@"attachment"

          contentType:@"image/png" isPublic:NO 

          successBlock:^(QBResponse *response, QBCBlob *blob) {

          __typeof(weakSelf)strongSelf = weakSelf;

        QBChatAttachment *attachment = [QBChatAttachment new];
        attachment.type = @"image";

        //IS IT POSSIBLE TO CAHNGE blob.UID TO [@(blob.ID) stringValue]????(as in older versions)
        attachment.ID = [@(blob.ID) stringValue]; //blob.UID
        
        attachment.url = [blob privateUrl];
        
        message.attachments = @[attachment];
        message.text = @"Attachment image";
        
        [strongSelf saveImageData:imageData chatAttachment:attachment error:nil];
        strongSelf.attachmentsStorage[attachment.ID] = image;
        
        [strongSelf changeMessageAttachmentStatus:QMMessageAttachmentStatusLoaded forMessage:message];
        
        [chatService sendMessage:message type:QMMessageTypeText toDialog:dialog saveToHistory:YES saveToStorage:YES completion:completion];
 
`

Prior to version 0.3.6 you were using  `attachment.ID = [@(blob.ID) stringValue]` 
After version 0.3.6 (include) you change it to `attachment.ID = blob.UID;`

**The problem**
Android users which use (deprecated) method:`QBContent.downloadFileById(fileId, params, new QBProgressCallback() ` [Android SDK](https://quickblox.com/developers/SimpleSample-content-android) will crash (because this method expect to get fileId as `int`)

**The Question**
Is it safe to update your SDK and use  `attachment.ID = [@(blob.ID) stringValue]` as you use prior to 0.3.6 temporary ???(as a work around for old Android users)

**Actual behavior**
Crash on Android which expect `attachment.ID` as `integer`

**Steps to reproduce the behavior**
install QMServices (0.3.6) and send attachment to android.

**Comment by Raikerian** [comment] 2017-07-20 15:13
Hi,

Will be fixed in the next release.

**Comment by Raikerian** [comment] 2017-07-20 15:16
My bad, it appears this is not SDK bug but our QMServices feature. By design QMServices UID in order to get all information by it. It will not be changed on our side but you are always welcome to fork and make the changes you want to. Crash on android should be sent here: https://github.com/QuickBlox/quickblox-android-sdk

**Closed** 2017-08-16 11:02 UTC
Labels: wontfix
