### ISSUE TITLE
message doesnt send

### ISSUE THREAD

**Issue by mrhaxic** [QuickBlox/quickblox-ios-sdk#322] opened 2016-03-05 00:59 UTC
Hi again .. 

I have this in AppDelegate
```

[QBSettings setApplicationID:36434];
    [QBSettings setAuthKey:@"dsad"];
    [QBSettings setAuthSecret:@"asdd"];
    [QBSettings setAccountKey:@"asdsda"];
    [QBSettings setLogLevel:QBLogLevelNothing];
    
    [QBRequest logInWithUserLogin:@"testuser" password:@"testuser" successBlock:^(QBResponse *response, QBUUser *user) {
        if (user) {
            user.login = @"testuser";
            user.password = @"testuser";
            // __typeof(self) strongSelf = weakSelf;
           [[QBChat instance] connectWithUser:user completion:^(NSError * _Nullable error) {
}
             ];
        }
    } errorBlock:^(QBResponse * _Nonnull response) {

    }];
```

and this to send message in another viewcontroller

```
 QBChatMessage *messagetosend = [QBChatMessage message];
    messagetosend.senderID = 10516336;
    messagetosend.senderNick = @"Andrey M.";
    messagetosend.text = @"test test";
    messagetosend.dateSent = [NSDate dateWithTimeInterval:-12.0f sinceDate:[NSDate date]];

    QBChatDialog *chatDialog = [[QBChatDialog alloc] initWithDialogID:@"56d9e95ba28f9a7bf5000058" type:QBChatDialogTypePublicGroup];

    [chatDialog joinWithCompletionBlock:^(NSError * _Nullable error) {
        [chatDialog sendMessage:messagetosend completionBlock:^(NSError * _Nullable error) {
            NSLog(@"%@",[error localizedDescription]);
        }];
 
    }];
```
    
I do not know why the message don't send to the dialog, I double check in dashboard there is no messages. btw sometimes this message show in the log

> [ChatService] Error RCV: <message xmlns="jabber:client" from="xx@muc.chat.quickblox.com" to="xx@chat.quickblox.com/xx" id="56da285ff8c58804110041a8" type="error"><body>Andrey M.
> would like to chat with you</body><error code="403" type="auth"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">**Insufficient privileges to send groupchat message**.</text></error></message>

**Comment by mrhaxic** [comment] 2016-03-05 01:11
@Raikerian please can you help me with this

**Comment by Raikerian** [comment] 2016-03-05 01:13
Hi,

First of all, how are you creating dialog? Where that ID came from?

**Comment by mrhaxic** [comment] 2016-03-05 01:17
@Raikerian I created from dashboard (Quickblox website)

**Comment by Raikerian** [comment] 2016-03-05 01:23
Check if dialog is actually public group. Also try to load dialog from rest (QBRequest method) and send message in it.

**Comment by mrhaxic** [comment] 2016-03-05 01:25
@Raikerian what do you mean by load dialog can you give me a hint or example ?

**Comment by Raikerian** [comment] 2016-03-05 01:26
Sure, use this method: https://sdk.quickblox.com/ios/documentation/Categories/QBRequest+QBChat.html#//api/name/dialogsForPage:extendedRequest:successBlock:errorBlock:

**Comment by Raikerian** [comment] 2016-03-05 01:28
You can use ID as the extended param (see here http://quickblox.com/developers/SimpleSample-chat_users-ios#Filters ) and load a correct instance of that dialog from server.

**Comment by mrhaxic** [comment] 2016-03-05 01:33
@Raikerian I'm really confused with this implementation if you can give me an example its will be appreciated

**Comment by Raikerian** [comment] 2016-03-05 01:35
You can see it in our QMServices: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMChatService/QMChatService/QMChatService.m#L980

**Comment by mrhaxic** [comment] 2016-03-05 01:59
@Raikerian I didn't get the point, I used PHP the message created well, but in iOS I think must make a session I don't know how can I do it :(

**Comment by mrhaxic** [comment] 2016-03-05 02:36
@Raikerian Please give me an example without QMService , I just use quickblox framework .. your support will be highly appreciated

**Comment by mrhaxic** [comment] 2016-03-05 11:37
any help ?

**Comment by Raikerian** [comment] 2016-03-05 12:50
Just take code from there, load dialog with it, and try to send a message in it. And tell us if it will work.

**Comment by Raikerian** [comment] 2016-03-07 09:03
Were you able to fix this issue? If not please create a test project with issue being reproducible and send it here.

**Comment by Raikerian** [comment] 2016-03-11 14:13
If you are still having troubles with this just reopen the issue, closing this for now due to tracking purposes.
If you are having any other troubles, feel free to create separate issue.

**Closed by Raikerian** 2016-03-11 14:13 UTC
Labels: needs further investigation
