### ISSUE TITLE
 Video call with Voip in terminated state

### ISSUE THREAD

**Issue by shoaibhassan1** [QuickBlox/quickblox-ios-sdk#1213] opened 2020-05-16 07:56 UTC
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

Dear Devs,
i have tested sample with VOIP notification by shifting all push kit code from UsersViewController to app delegate,
Voip notification receives on device,call kit shown, call accepted, call gets connected but with audio only,both sides can see there own video but not other peers video
but audio is working fine.

Anybody face same issue or any help will be appreciated.
Thanks

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:52
@shoaibhassan1 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:52 UTC
