### ISSUE TITLE
Activating audio session config changes audio output from headphones to receiver

### ISSUE THREAD

**Issue by maughray** [QuickBlox/quickblox-ios-sdk#1283] opened 2021-07-05 12:46 UTC
**New Issue Checklist**

 - [+] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [+] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

Before call, audio output is selected as headphones, but when activating below config it is set to recever. How to continue use headphones for call?

```
let config = QBRTCAudioSessionConfiguration()
config.mode = AVAudioSession.Mode.videoChat.rawValue
config.category = AVAudioSession.Category.playAndRecord.rawValue
config.categoryOptions = [.allowBluetooth, .allowBluetoothA2DP, .allowAirPlay]
```

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:55
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:55 UTC
