### ISSUE TITLE
QBChatDialog unreadMessagesCount issue after disconnecting chat.

### ISSUE THREAD

**Issue by matrosovDev** [QuickBlox/quickblox-ios-sdk#350] opened 2016-03-17 18:34 UTC
Yo dudes, thanks for help on my previous question, I really appreciate it. So currently the question is the same as previous regarding `- (void)disconnectWithCompletionBlock:(QBChatCompletionBlock)completion;`

But right now it's connected to unreadMessages count. It works perfect if we don't disconnect chat and then reopen it.

So let me describe my actions:
1. So I move app to background with disconnecting a chat using method above.
2. Send message from user B and Push Notification message appears on my home screen.
3. Then I open app immediately while seeing top push notification field on home screen by pressing app icon.
4. App try to connect chat one more time `- (void)connectWithCompletionBlock:(QBChatCompletionBlock)completion;`
5. After completion I try to get unread messages from QBChatDialog unreadMessagesCount but by some reason it's 0 for all QBChatDialog dialogs.

One more if I don't disconnect chat and move app to background all work perfect even with updating badge counters over app icon, but the Push Notification never appears.

Thanks for help!

**Comment by iSevenDays** [comment] 2016-03-18 08:02
Hi matrosovDev,

We need some more information from you to reproduce the issue.

> 5. After completion I try to get unread messages from QBChatDialog unreadMessagesCount but by some reason it's 0 for all QBChatDialog dialogs.

1. QBChatDialog does not update unreadMessagesCount by itself, you should call [QBRequest totalUnreadMessageCountForDialogsWithIDs:successBlock:errorBlock]

2. Did QBChatDialog has unreadMessagesCount for example 5, but after disconnect it showed 0? If yes, please give us logs or sample test project if available

Thanks!

**Comment by matrosovDev** [comment] 2016-03-18 16:38
Hey seem `totalUnreadMessageCountForDialogsWithIDs` works. For getting all unread messages, but I guess it means that if I need to display unread messages for concrete dialog then I need to invoke the same just for one dialog and send as many request as I need to get all unread messages for all chats. Right?

**Comment by Raikerian** [comment] 2016-03-20 11:44
Hi,

You can achieve a correct number in unreadMessagesCount by managing it manually after each message receive. We have such feature available in our [QMServices](https://github.com/QuickBlox/q-municate-services-ios), check them out.

**Comment by matrosovDev** [comment] 2016-03-22 12:40
Let me also few details that I've added to the quickblox assist system as a ticket:

Let me describe situation:

1. I message from user A to user B when both application are active. Everything works good on this step and I correct unread messages count. Unread message count = 1.

2. When I move app to background for user A and then send a message from user B then it show correct application badge number after receiving push notification. Unread message count = 2.

3. Reopen app and send message from user B again to user A. Works good. Unread message count = 3.

4. Move app to background and try to send message from user B to user A. It looks like on this step when we receive app something work wrong because Unread message count = 1 for application icon badge.

For checking if this problem on iOS side I request all unread messages for all dialogs via `totalUnreadMessageCountForDialogsWithIDs` and it returns 1 unread message count, but should be 4

Thanks for help, let me know if you need additional details.

**Comment by Raikerian** [comment] 2016-03-22 12:50
@matrosovDev it could be a server issue, however it will be helpful if you will send us some logs, that will represent the issue.

**Comment by matrosovDev** [comment] 2016-03-23 12:43
Well, I am not sure what logs do you need. Because I just did those steps and using QBRequest I requested unread messages from API and it returns for me not correct data, it decrees badge number even without my action.

**Comment by Raikerian** [comment] 2016-03-23 12:58
You mentioned that:

> For checking if this problem on iOS side I request all unread messages for all dialogs via totalUnreadMessageCountForDialogsWithIDs and it returns 1 unread message count, but should be 4

This means, that the server badge is incorrect too (by server badge I mean QBRequest result). Am I right?

**Comment by matrosovDev** [comment] 2016-03-23 13:49
yea I see new notification on my home screen and it decrease alert message count. I guess payload already has some wrong data amount. I can say that I have not marked messages as read, but I have new unread messages amount which is less than before disconnecting.

**Comment by matrosovDev** [comment] 2016-03-25 13:19
one more issue that I found that after I call `QMServicesManager.instance().chatService.readMessages(messages, forDialogID: dialogID) {(error) in`
it does not mark message as read.

**Comment by Raikerian** [comment] 2016-03-25 15:01
It is working as intended in our samples. If you are experiencing some problems with this method, please provide us full logs that will represent the issue.

**Comment by matrosovDev** [comment] 2016-03-25 15:42
I've tested it using your example

http://screencast.com/t/PUUdJmpRnkr

**Comment by matrosovDev** [comment] 2016-03-25 15:43
one more here when dialog never update count of unread message http://screencast.com/t/ZnuAWNVhbi

**Comment by Raikerian** [comment] 2016-03-25 15:46
We are performing read message in our samples only if message is visible on screen. Scroll through all messages in chat controller and unread counter will be updated cause messages status will also update.

**Comment by matrosovDev** [comment] 2016-03-25 16:00
yea you see I scrolled through all messages on the second video?

**Comment by Raikerian** [comment] 2016-03-25 16:34
Try to reproduce this issue again (remove all cache first) and catch all logs this time and attach them here. Then we will have something to look into, and will be trying to reproduce it.
Right now I cannot catch the problem, and I think that there is some kind of specific case in your occasion.

**Comment by matrosovDev** [comment] 2016-03-25 17:05
Ok thanks, how can I remove cache?

**Comment by Raikerian** [comment] 2016-03-25 17:06
If you haven't modified our samples code had, just perform logout and login again. Otherwise reinstall application.

**Comment by matrosovDev** [comment] 2016-03-28 10:12
yea, tried it a lot of times. even reset simulator. for some dialogs it works without any problem, but for some dialogs there are unread messages still.

**Comment by Raikerian** [comment] 2016-03-28 10:24
We are currently investigating the issue and will post update soon.

**Comment by matrosovDev** [comment] 2016-03-30 14:48
Hey guys, do you have some updates? or maybe you need some details, thanks!

**Comment by iSevenDays** [comment] 2016-03-30 14:53
Hi @matrosovDev 

We found the root of the issue.

We have an issue that we download messages using lt (Less Than) operator

If messages have the same date_sent, then we will skip that messages.

For example

1 Download 5 messages
A Date 10.10.00
B Date 10.10.01
C Date 10.10.02
D Date 10.10.03
E Date 10.10.03 <-- Here we reached our limit of 5 messages to download
F Date 10.10.03
G Date 10.10.04

Next time message F will be skipped, because we use operator Less Than date 10.10.03

We should change it to Less Than or Equal "lte" operator.

But we found some bugs and we should fix them.

Thanks!

**Comment by matrosovDev** [comment] 2016-03-30 14:57
sweet! thanks guys for quick response on it, appreciate it! looking forward for updates)

**Comment by matrosovDev** [comment] 2016-04-11 17:11
Hey guys! have you chance to update pods?)

**Comment by Raikerian** [comment] 2016-04-12 07:55
Hi @matrosovDev 

This issue is not about pods. We are currently waiting for a server-side fix (ETA today) and then we will be able to fix it on our side.

**Comment by matrosovDev** [comment] 2016-04-12 08:17
oh, sorry I've posted to another issue, as we have another one that is connected to pods
ok thanks!)

**Comment by Raikerian** [comment] 2016-04-15 17:20
@matrosovDev Fixed in QMChatViewController 0.3.6 and QMServices 0.3.9. Checkout also our latest samples in master branch.

**Closed by Raikerian** 2016-04-15 17:20 UTC
Labels: bug
