### ISSUE TITLE
Push notifications are not delivered suddenly

### ISSUE THREAD

**Issue by vanywhere** [QuickBlox/quickblox-ios-sdk#1235] opened 2020-09-20 21:47 UTC
**New Issue Checklist**

 - [v] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [v] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

iOS SDK

Hi QB Team,

Push notifications are not delivered for the last few days. It worked before. We did not make any changes. While testing it a couple of days ago came back and worked for an hour, but stopped working and never came back since.

APNS works as expected, and I tried sending a notification via your QuickBlox admin panel and it didn't work.

In queue tab, status of the message is sent but it is not delivered on phone. When pressing on 'sent' - I see APNS VoIP (Apple Push VoIP) Delivered: 0, failed: 0.

In the log, you can also see: "delivered":null,"delivered_at":null

Thanks

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:49
@vanywhere The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:49 UTC
