### ISSUE TITLE
rear camera image upside down in landscape

### ISSUE THREAD

**Issue by gravitypushes** [QuickBlox/quickblox-ios-sdk#43] opened 2015-01-07 04:33 UTC
User1 rear camera image displays upside down on User2 device when User1 puts device in landscape.
This issue can be replicated by using the Video Chat test app.
1) user1 calls user2.
2) user1 chooses "Back" for video output
3) user1 puts device into landscape mode.
4) the image on user2 device will be flipped.
this issue does not occur when user1 chooses "face" for video output

**Comment by pzoechner** [comment] 2015-01-18 18:23
Duplicate of [#26](https://github.com/QuickBlox/quickblox-ios-sdk/issues/26)

**Comment by soulfly** [comment] 2015-04-10 20:55
New generation of Video samples is here http://quickblox.com/developers/VideoChat

**Closed by soulfly** 2015-04-10 20:55 UTC
