### ISSUE TITLE
taking to much time to establish  audio/video call

### ISSUE THREAD

**Issue by kirti301290** [QuickBlox/quickblox-ios-sdk#1227] opened 2020-08-10 07:31 UTC
iOS Version                    13.5                                 
QuickbloxWebRTC SDK version   2.7.5              
Xcode Version                 Xcode 11.5

Hello 
we facing problem  4-5 sec delay  establish  audio/video call and having good internet connection 
for example  UserA calling to UserB and  UsedB Accepted call but  it taking 4-5 sec to connection
Thanks

**Comment by KiranPatelSpaceo** [comment] 2020-08-17 09:33
I have same issue

**Comment by maughray** [comment] 2020-09-23 12:43
I also have the same issue.

**Comment by Navya-ios** [comment] 2020-10-06 10:16
same issue

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:50
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:50 UTC
