### ISSUE TITLE
[Call Answer] not working 

### ISSUE THREAD

**Issue by chandaboy786** [QuickBlox/quickblox-ios-sdk#1219] opened 2020-06-22 15:38 UTC
2020-06-22 20:36:31.213551+0500 TAG[1920:286296] [BackgroundTask] Background Task 14 ("Called by QuickbloxWebRTC, from qb_create_dispatch_timer"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

I am running code but right now it is closing after some time and I am getting status of NoAnswer.

I have follow documentation but it is not working.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:51
@chandaboy786 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:51 UTC
