### ISSUE TITLE
Stop call or ringing while accept call in another device same login id

### ISSUE THREAD

**Issue by Rushang007** [QuickBlox/quickblox-ios-sdk#1181] opened 2019-10-15 08:38 UTC
Currently, I'm doing a one calling project and I'm facing an issue in one scenario :

Scenario : Let's say I have logged-in an App from two different Mobile devices. Just consider the App is Skype for a while. Now, whenever I receive a call, then both the devices rang (which is obvious). But, when I accept a call from one device, then the other keeps on ringing. So, can you help me with how I can stop the ring of the other device as soon as I answered or accept the call from one device ?

#Swift
#Audio&VideoCall

**Comment by QB-vladyslav-vyshniak** [comment] 2019-10-28 16:06
Hello @Rushang007 

Thank you for contacting QuickBlox support.

Could you provide me with the detailed logs (which cover all the described behavior) and code snippet. 
What IOS SDK version do you use? 

Looking forward to your reply.

**Comment by Rushang007** [comment] 2019-10-30 06:02
@QB-vladyslav-vyshniak  Thanks For Reply 

1. I think for this scenario do not need any log
2.  IOS SDK version latest

**Comment by QB-vladyslav-vyshniak** [comment] 2019-11-05 11:37
@Rushang007 

Please, provide me with the detailed logs - only then the developers will start the investigation process. 
Also, I need the detailed steps to reproduce the reported behavior (step by step description). 

Looking forward to your reply.

**Comment by Rushang007** [comment] 2019-11-05 11:52
Hi @QB-vladyslav-vyshniak. Actually, the thing is I haven't coded yet. What I want is to know how I execute this functionality which I mentioned earlier. There is nothing related to auto-reject the session when it's already active in another device. The same scenario is available in Javascript but not for the iOS SDK. Please find the attachment

![Screenshot 2019-11-05 at 5 20 13 PM](https://user-images.githubusercontent.com/16713953/68205645-d3abdb00-fff0-11e9-96f6-d8e097b75d5b.png)
.

**Comment by QB-vladyslav-vyshniak** [comment] 2020-02-17 15:58
Hello @Rushang007

Is the asked question still relevant for you or could be "Closed"?

**Comment by Rushang007** [comment] 2020-04-15 15:35
@QB-vladyslav-vyshniak  Still not happening please help

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:40
@Rushang007 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:40 UTC
