### ISSUE TITLE
Crash on Receiving Video call session 

### ISSUE THREAD

**Issue by meAbhishekTripathi** [QuickBlox/quickblox-ios-sdk#1226] opened 2020-07-28 13:43 UTC
**Getting crash on receiver side when created session for Video call on sender side. Delegate of didReceiveNewSession not called before crashing. It means It somewhere crashing on getting the session.**

Here is the crash log :

2020-07-28 09:38:22.896 rtc::Create audio track: RTCMediaStreamTrack:
audio
audioTrack
enabled
Live
2020-07-28 09:38:22.897 rtc::[CAPT] Init.
2020-07-28 09:38:22.897 rtc::Create video track: RTCMediaStreamTrack:
video
videoTrack
enabled
Live
2020-07-28 09:38:22.899 rtc::initialize - QBRTCRecorder
2020-07-28 09:38:22.964 rtc::[SESS]<EAE09BD2-1FBD-44B0-AC56-4E246A70E556, I:117933348, O:[117932948], T:V> Init.
2020-07-28 09:38:22.967 rtc::[TASK]<ID:5, l:session answer time out> Start.
2020-07-28 09:38:22.967 rtc::[RTCClient] <QBRTCClient: 0x280b67300> created new [SESS]<EAE09BD2-1FBD-44B0-AC56-4E246A70E556, I:117933348, O:[117932948], T:V>
2020-07-28 09:38:22.968801-0400 HQDemand[6281:683068] -[__NSCFConstantString count]: unrecognized selector sent to instance 0x102fc7d50
2020-07-28 09:38:44.303310-0400 HQDemand[6281:683068] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString count]: unrecognized selector sent to instance 0x102fc7d50'
*** First throw call stack:
(0x1c22b3180 0x1c148b9f8 0x1c21cf9bc 0x1c22b89c8 0x1c22ba65c 0x1efff085c 0x1effe5e6c 0x101219ed8 0x1c22ba800 0x1c219c3c0 0x1c219cff4 0x102f4a5e4 0x10764f6f4 0x107650c78 0x10765e6fc 0x1c2244b20 0x1c223fa58 0x1c223efb4 0x1c444079c 0x1eeaa0c38 0x101090bac 0x1c1d028e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by rorodriguez116** [comment] 2020-07-29 21:52
I'm receiving the exact same error on the callee side. iOS app crashes with same error.

**Comment by meAbhishekTripathi** [comment] 2020-07-30 05:11
@rorodriguez116  When you create session from the caller side, make sure you pass nil or use NSString not String.

**Comment by rorodriguez116** [comment] 2020-07-30 06:23
@meAbhishekTripathi, Thanks for the suggestion.

**Comment by shubhashkspaceo** [comment] 2020-08-28 04:52
I have fetching same issue when call initiate from web and in iOS app is crashed.

**Comment by seshukumarpoluparthi** [comment] 2020-09-28 10:17
when call is initiated,while receiving side my app got crashed , i didnt even dubug it where the error is 

this the error i got:
Could not cast value of type '__NSDictionaryM' (0x1eb48b050) to 'NSString' (0x1eb493f18)

this is the log:


2020-09-28 15:44:03.999 rtc::[Signaling Processor] - Did receive signal: call from: 25156065
2020-09-28 15:44:04.005 rtc::[RTCClient] Initializing SSL...
2020-09-28 15:44:04.006 rtc::Create audio track: RTCMediaStreamTrack:
audio
audioTrack
enabled
Live
2020-09-28 15:44:04.006 rtc::[CAPT] Init.
2020-09-28 15:44:04.007 rtc::Create video track: RTCMediaStreamTrack:
video
videoTrack
enabled
Live
2020-09-28 15:44:04.008 rtc::initialize - QBRTCRecorder
2020-09-28 15:44:04.010 rtc::[SESS]<51b11c9a-8be4-49aa-ae4e-d907a929f659, I:25156065, O:[25158778], T:V> Init.
2020-09-28 15:44:04.011 rtc::[TASK]<ID:17, l:session answer time out> Start.
2020-09-28 15:44:04.011 rtc::[RTCClient] <QBRTCClient: 0x280018540> created new [SESS]<51b11c9a-8be4-49aa-ae4e-d907a929f659, I:25156065, O:[25158778], T:V>

> Could not cast value of type '__NSDictionaryM' (0x1eb48b050) to 'NSString' (0x1eb493f18).

2020-09-28 15:44:04.012525+0530[13846:2275372] Could not cast value of type '__NSDictionaryM' (0x1eb48b050) to 'NSString' (0x1eb493f18).

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:50
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:50 UTC
