### ISSUE TITLE
Updating full name gives 422 error

### ISSUE THREAD

**Issue by ahmetws** [QuickBlox/quickblox-ios-sdk#693] opened 2016-12-05 22:30 UTC
Trying to update user info gives 422 error. Here is my code: 

```
              let updateParameters = QBUpdateUserParameters()
                updateParameters.fullName = self.txtDisplayNameField.text!
                QBRequest.updateCurrentUser(updateParameters, successBlock: { (response: QBResponse, user: QBUUser?) -> Void in
                    // Save User Info
                    }, errorBlock: { (response: QBResponse) -> Void in
                    // Fail

                })

```
**Environment details**
*iOS version, Quickblox iOS SDK version
iOS 10, QuickBlox 2.9

**Did this work before?**
no idea

**Expected behavior**
update the user fullName

**Actual behavior**
Error

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*
po response.error
▿ Optional<QBError>
  - Some : 
   Error reasons:{
    errors =     {
        blob =         (
            "does not exist"
        );
    };
}

**Comment by Raikerian** [comment] 2016-12-06 09:54
Hi,

Print `[QBSession currentSession].currentUser` before after that request, is there a correct user? Does it exist on server?

**Comment by ayalcinkaya** [comment] 2016-12-06 10:08
Yes, there is actually a current user. The problem is why is that code checking if a blob exist or not. Isn't this code just update the fullName here ?

**Comment by Raikerian** [comment] 2016-12-06 10:11
Blob is basically entity on our server, which is user in the current case. Can you catch full logs from app start till error? Need to see detailed logs on this.

Also check if user is existent in admin panel.

**Comment by ayalcinkaya** [comment] 2016-12-09 17:27
Here is the logs:

2016-12-09 20:25:07.971 app[349:41701] [QBCore] Request URL:https://api.quickblox.com/users/20409143.json
2016-12-09 20:25:07.972 app[349:41701] [QBCore] Request method: PUT
2016-12-09 20:25:07.972 app[349:41701] [QBCore] Request parameters:{
    user =     {
        "full_name" = ahmrtasda;
        "tag_list" = "";
    };
}
2016-12-09 20:25:07.973 app[349:41701] [QBCore] Request headers: {
    "Accept-Language" = "en-TR;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.1";
    "QB-SDK" = "iOS 2.9";
    "QB-Token" = ef81854512db753cbb47b6c31ef7ffd1d400bb2c;
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "app/1.0.1 (iPhone; iOS 10.1; Scale/2.00)";
}
2016-12-09 20:25:08.283 app[349:39962] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x170630ec0> { URL: https://api.quickblox.com/users/20409143.json } { status code: 422, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 38;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 09 Dec 2016 17:25:08 GMT";
    "QB-Token-ExpirationDate" = "2016-12-09 19:13:39 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "422 Unprocessable Entity";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 31095dd1999cdf244d2ce530675fc6e1;
    "X-Runtime" = "0.055935";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/users/20409143.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 626c6f62 223a5b22 646f6573 206e6f74 20657869 7374225d 7d7d>, NSLocalizedDescription=Request failed: client error (422)}
2016-12-09 20:25:08.285 app[349:39962] [QBCore] Response error reasons: {
    errors =     {
        blob =         (
            "does not exist"
        );
    };
}

**Comment by ayalcinkaya** [comment] 2016-12-09 17:34
The user seems correct on the QB Admin Panel but when I try to change this user from the panel it gives exactly same error: Error - Blob does not exist.

**Comment by Raikerian** [comment] 2016-12-12 10:57
Is it correct for all users, or only for a specific one?

**Comment by ayalcinkaya** [comment] 2016-12-12 11:41
This happens some of the user in the database. Not all of them

**Comment by Raikerian** [comment] 2016-12-14 15:45
As this is happens in admin panel too, this is surely a server side issue and not iOS SDK related. I suspect you are using our dedicated plan. If you are still haven't reported it in our enterprise support, you sure need to do it. Let me know if you have done this.

**Comment by Raikerian** [comment] 2016-12-14 16:24
I was reported that the issue will be fixed in a nearest server-side release soon.

**Closed** 2017-01-11 10:52 UTC
Labels: server side issue
