### ISSUE TITLE
chatDidReceiveMessage and chatDidDeliverMessageWithID are not being called

### ISSUE THREAD

**Issue by adil-appifytech** [QuickBlox/quickblox-ios-sdk#622] opened 2016-10-19 11:41 UTC
**Environment details**
_iOS version, Quickblox iOS SDK version, QuickbloxWebRTC SDK version (optional)_
*iOS 8.0, Quickblox iOS SDK 2.8.0.1

**Did this work before?**
Yes

**Expected behavior**
`chatDidReceiveMessage` should be called on receiver end and `chatDidDeliverMessageWithID` should be called on sender end.

**Actual behavior**
Above mentioned objects are not being called.

**Logs**
To share the logs, please tell me some non-public forum. 

**Steps to reproduce the behavior**
Send the message

**Comment by Raikerian** [comment] 2016-10-19 13:10
Hi @adil-appifytech 

More information is necessary to understand your issue.
1. Have you subscribed to chat delegate?
2. Is this issue reproducible in our samples?
3. Any logs you can provide (full logs preferably).

**Comment by adil-appifytech** [comment] 2016-10-20 06:32
Hi @Raikerian

1. Yes I have (I am getting other callbacks like `chatContactListDidChange` etc)
2. No I am not able to produce them there because your samples are using older version of Quickblox (maybe this is with new SDK)
3. Since we are using enterprise version, I can't share the logs in detail but here is the pic. (Please tell me how I can share detailed logs in private)

![screen shot 2016-10-20 at 11 26 34 am](https://cloud.githubusercontent.com/assets/10629648/19548497/56aa37d6-96b8-11e6-87b3-f9d44f4e1e76.png)

**Comment by Raikerian** [comment] 2016-10-20 10:18
Our samples in master branch are using latest version of QB iOS SDK 2.8.0.1.
You can check it there.

Also, we don't have such problems in our project, so logs is where we should start.
You can mail them to me: raikerian@gmail.com

**Comment by adil-appifytech** [comment] 2016-10-20 11:14
@Raikerian - Your sdk samples are using https://github.com/QuickBlox/q-municate-services-ios and they are still using 2.6.5 - https://github.com/QuickBlox/q-municate-services-ios/tree/master/Frameworks

**Comment by Raikerian** [comment] 2016-10-20 11:15
You referred to our QMServices repository, it is not samples. Nad that SDK is just a placeholder without binaries to make our cache compilable.
Our samples are placed in current repository which contains our latest SDK :)

**Comment by adil-appifytech** [comment] 2016-10-20 12:07
@Raikerian - I ran the sample code and sender is not getting `chatDidDeliverMessageWithID` callback (though message is being saved somehow on sender side)

Here are the logs.
https://gist.github.com/adil-appifytech/d96a6aa2d31d60534e209fb72507333b

**Comment by Raikerian** [comment] 2016-10-20 12:09
`chatDidDeliverMessageWithID ` is only being called if receiver has marked message as delivered using `[QBChat markMessageAsDelivered:]` method. Have you marked it?

**Comment by adil-appifytech** [comment] 2016-10-20 12:15
@Raikerian - I am running your sample code. So I have not checked it. And in previous versions, `chatDidDeliverMessageWithID` was called as soon as opponent get it. I believe now it's behavior has been changed?

**Comment by Raikerian** [comment] 2016-10-20 12:22
No, it should be the same if your opponent is currently online. Here is the line of code which triggers it: https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMManagers/QMServicesManager.m#L225 (again, this are not samples, it is our wrapper project which is used in samples in current repository).

Whenever opponent gets message while he is online, he is marking that message as delivered.

**Comment by adil-appifytech** [comment] 2016-10-26 05:59
@Raikerian - Please share your Quickblox email if possible. I can't share logs on personal email. Thanks.

**Comment by Raikerian** [comment] 2016-10-26 07:51
@adil-appifytech share your logs through our support team.

**Comment by adil-appifytech** [comment] 2016-10-26 08:25
@Raikerian - Well support team is extremly slow :(

**Comment by Raikerian** [comment] 2016-10-27 15:19
Well, the problem is not existent in our samples.
If chatDidReceiveMessage wasn't working, our samples would not receive any private messages (but they do). And chatDidDeliverMessageWithID is also working as intended.

For your project I can suggest to double check whether you are subscribed to a chat delegate (call delegates property of QBChat). Also try to redeclare those both methods in your code, maybe their style was changed a bit and swift doesn't understand a new one.

**Comment by Raikerian** [comment] 2016-11-02 13:29
@adil-appifytech have you tried my advice? Any results?

**Comment by adil-appifytech** [comment] 2016-11-03 05:14
@Raikerian - We have send the sample code to support team and they are looking into the matter.

**Comment by Pro100Andrey** [comment] 2016-11-08 12:27
@adil-appifytech Resolved with support team

**Closed by Pro100Andrey** 2016-11-08 12:27 UTC
Labels: needs further investigation
