### ISSUE TITLE
App crash on lastActivityDate

### ISSUE THREAD

**Issue by mohsinalimat** [QuickBlox/quickblox-ios-sdk#691] opened 2016-12-05 06:41 UTC
Hello,

Terminating app due to an uncaught exception 'NSInvalidArgumentException', reason: '-[QMServicesManager setLastActivityDate:]: unrecognized selector sent to instance 0x17405bae0'

This crash issue is on when app is on live app store...

Thanks,
Mohsinali Matiya

**Comment by Pro100Andrey** [comment] 2016-12-07 11:19
Hi @mohsinalimat i don't see `[QMServicesManager setLastActivityDate: ` in [QMServicesManager.h](https://github.com/QuickBlox/q-municate-services-ios/blob/master/QMManagers/QMServicesManager.h)

**Comment by Pro100Andrey** [comment] 2016-12-07 11:30
@mohsinalimat i see `setLastActivityDate` in [ServicesManager.h]( https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/sample-chat/sample-chat/Services/ServicesManager.h#L30) but this not static method, please check your implementation

**Comment by Raikerian** [comment] 2016-12-14 15:22
Closing due to lack of user response. If you are still experiencing this issue, create a new thread with logs being attached. If that issue is not reproducible in our samples, please attach any sample project with it being reproducible.

**Closed by Raikerian** 2016-12-14 15:22 UTC
Labels: invalid
