### ISSUE TITLE
Sending message in deleted dialog creates and new dialog

### ISSUE THREAD

**Issue by pooja1bhatia** [QuickBlox/quickblox-ios-sdk#1295] opened 2021-10-01 10:54 UTC
**New Issue Checklist**

 - [ ] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [ ] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 14.0                                    |                                          
Quickblox iOS SDK version      | e.g. 2.7.10                                   |                         
Xcode Version                  | e.g. Xcode 12.5.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
No

**Expected behavior**

If in private chat either one user deletes a dialog, then the other user should receive a delegate for the success of the delete dialog or if an opponent sends a message in a deleted dialog then it should not create a new dialog on both ends.

**Actual behavior**

In private chat, on delete dialog from one side,deletes dialog for both users. But the opponent doesn't get any ping for the delete dialog. If one user is on chat screen and other user deletes dialog then that dialog deleted successfully and updates UI on sender side (who deleted dialog) but if other user is on chat screen and on the same time he sent message in same dialog then message sent successfully and it automatically creates new dialog.

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**

- Create a private dialog.
- On one end open the chat screen and on other side delete dialog.
- Now from the chat screen, send a message in the dialog which is actually deleted and does not exist in the QB database.
- Now a new dialog with the new dialog id created and it will start to appear on both users.

**Any others comments**

**Comment by QB-vladyslav-vyshniak** [comment] 2021-10-06 09:16
Hello Pooja. 

Thank you for contacting QuickBlox Customer Support department. 

In order to start the investigation of the reported case QuickBlox Development team needs the following points. 

1. Could you try to reproduce the reported behavior using a clear QuickBlox IOS Chat sample URL: https://docs.quickblox.com/docs/ios-quick-start#chat-samples and let us know about a result there. 
2. Collect the full logs from the application launching till the issue occurs in .txt format file where the developers could observe the described behavior (error) using the following method, URL: https://docs.quickblox.com/docs/ios-setup#enable-logging 

Looking forward to your reply with the requested points.

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-07 14:54
@pooja1bhatia The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed by QB-nikolay-zolotarov** 2021-12-07 14:54 UTC
